"""Realm export — oauth2-proxy config and nginx snippet."""

from __future__ import annotations

import json
from pathlib import Path

from sqlalchemy.orm import Session

from app.models import RealmConfig
from app.secret_crypto import decrypt_secret, encrypt_secret, generate_cookie_secret
from app.sso_settings import Settings


def compute_redirect_uri(slug: str, settings: Settings) -> str:
    return f"https://{settings.portal_domain}/oauth2/{slug}/callback"


def _exports_path(settings: Settings) -> Path:
    path = Path(settings.exports_dir)
    path.mkdir(parents=True, exist_ok=True)
    return path


def _ensure_cookie_secret(realm: RealmConfig, settings: Settings) -> str:
    if realm.oauth2_cookie_secret_encrypted:
        return decrypt_secret(realm.oauth2_cookie_secret_encrypted, settings)
    secret = generate_cookie_secret()
    realm.oauth2_cookie_secret_encrypted = encrypt_secret(secret, settings)
    return secret


def generate_oauth2_proxy_config(realm: RealmConfig, settings: Settings) -> str:
    client_secret = decrypt_secret(realm.client_secret_encrypted, settings)
    cookie_secret = _ensure_cookie_secret(realm, settings)
    lines = [
        f"# Generated for realm: {realm.slug}",
        f"http_address = \"127.0.0.1:{realm.oauth2_proxy_port}\"",
        "upstream = \"http://127.0.0.1:8000\"",
        'provider = "oidc"',
        f'oidc_issuer_url = "{realm.issuer_url}"',
        f'client_id = "{realm.client_id}"',
        f'client_secret = "{client_secret}"',
        f'redirect_url = "{realm.redirect_uri}"',
        f'cookie_secret = "{cookie_secret}"',
        f'scope = "{realm.scopes}"',
        "email_domains = [\"*\"]",
        "cookie_secure = true",
        "cookie_httponly = true",
        "set_xauthrequest = true",
        "pass_access_token = false",
        "pass_authorization_header = true",
        "",
    ]
    return "\n".join(lines)


def generate_nginx_realms_conf(db: Session) -> str:
    realms = db.query(RealmConfig).filter_by(enabled=True).all()
    lines = ["# Generated by realm_service — do not edit manually", ""]

    for realm in realms:
        lines.append(f"# Realm: {realm.slug} ({realm.name})")
        lines.append(f"location /oauth2/{realm.slug}/ {{")
        lines.append(f"    proxy_pass {realm.oauth2_proxy_url}/oauth2/;")
        lines.append("    proxy_set_header Host $host;")
        lines.append("    proxy_set_header X-Real-IP $remote_addr;")
        lines.append("    proxy_set_header X-Forwarded-Proto $scheme;")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def export_realm_files(realm: RealmConfig, db: Session, settings: Settings) -> dict[str, str]:
    exports_path = _exports_path(settings)
    proxy_config_path = exports_path / f"oauth2-proxy-{realm.slug}.conf"
    nginx_path = exports_path / "nginx-portal-realms.conf"

    proxy_config_path.write_text(
        generate_oauth2_proxy_config(realm, settings), encoding="utf-8"
    )
    nginx_path.write_text(generate_nginx_realms_conf(db), encoding="utf-8")

    return {
        "oauth2_proxy_config": str(proxy_config_path),
        "nginx_realms_conf": str(nginx_path),
    }


def persist_test_result(realm: RealmConfig, result: dict) -> None:
    realm.last_test_status = result["status"]
    realm.last_test_detail = json.dumps(result, ensure_ascii=False)
    from app.models import utcnow

    realm.last_tested_at = utcnow()
