"""Realm export — oauth2-proxy config and nginx snippet."""

from __future__ import annotations

import json
from pathlib import Path

from sqlalchemy.orm import Session

from app.models import RealmConfig
from app.secret_crypto import decrypt_secret, encrypt_secret, generate_cookie_secret
from app.sso_settings import Settings


def compute_redirect_uri(slug: str, settings: Settings) -> str:
    return f"https://{settings.portal_domain}/oauth2/{slug}/callback"


def _exports_path(settings: Settings) -> Path:
    path = Path(settings.exports_dir)
    path.mkdir(parents=True, exist_ok=True)
    return path


def _ensure_cookie_secret(realm: RealmConfig, settings: Settings) -> str:
    if realm.oauth2_cookie_secret_encrypted:
        return decrypt_secret(realm.oauth2_cookie_secret_encrypted, settings)
    secret = generate_cookie_secret()
    realm.oauth2_cookie_secret_encrypted = encrypt_secret(secret, settings)
    return secret


def realm_oauth2_proxy_url(realm: RealmConfig, settings: Settings) -> str:
    """Resolve oauth2-proxy base URL for nginx / FastAPI auth_request."""
    if settings.oauth2_proxy_network_mode == "docker":
        if realm.slug in core_static_realm_slugs(settings):
            return "http://oauth2-proxy-core:4180"
        return f"http://oauth2-proxy-{realm.slug}:4180"
    return f"http://127.0.0.1:{realm.oauth2_proxy_port}"


def generate_oauth2_proxy_config(realm: RealmConfig, settings: Settings) -> str:
    client_secret = decrypt_secret(realm.client_secret_encrypted, settings)
    cookie_secret = _ensure_cookie_secret(realm, settings)
    if settings.oauth2_proxy_network_mode == "docker":
        http_address = "0.0.0.0:4180"
    else:
        http_address = f"127.0.0.1:{realm.oauth2_proxy_port}"
    lines = [
        f"# Generated for realm: {realm.slug} — source of truth: DB RealmConfig (do not edit)",
        f'http_address = "{http_address}"',
        # auth_request-only: no reverse proxy to FastAPI (Nginx handles app traffic)
        'upstreams = [ "file:///dev/null" ]',
        "reverse_proxy = true",
        "skip_provider_button = true",
        'provider = "oidc"',
        f'oidc_issuer_url = "{realm.issuer_url}"',
        f'client_id = "{realm.client_id}"',
        f'client_secret = "{client_secret}"',
        f'redirect_url = "{realm.redirect_uri}"',
        f'cookie_secret = "{cookie_secret}"',
        # Keycloak PKCE — required when client enforces code_challenge_method
        'code_challenge_method = "S256"',
        f'scope = "{realm.scopes}"',
        "email_domains = [\"*\"]",
        "cookie_secure = true",
        "cookie_httponly = true",
        "set_xauthrequest = true",
        "pass_access_token = false",
        "pass_authorization_header = true",
        "",
    ]
    return "\n".join(lines)


def core_static_realm_slugs(settings: Settings) -> frozenset[str]:
    """Realm slugs served by oauth2-proxy-core (nginx snippet static; oauth2 cfg still from DB)."""
    if not settings.oauth2_core_static_enabled:
        return frozenset()
    return frozenset({settings.sso_portal_default_realm_slug})


def generate_nginx_realms_conf(
    db: Session,
    settings: Settings,
    *,
    exclude_slugs: frozenset[str] | None = None,
) -> str:
    realms = db.query(RealmConfig).filter_by(enabled=True).order_by(RealmConfig.slug).all()
    if exclude_slugs:
        realms = [realm for realm in realms if realm.slug not in exclude_slugs]
    lines = ["# Generated by realm_service — do not edit manually", ""]

    for realm in realms:
        proxy_base = realm_oauth2_proxy_url(realm, settings)
        lines.append(f"# Realm: {realm.slug} ({realm.name})")
        lines.append(f"location ^~ /oauth2/{realm.slug}/ {{")
        lines.append("    auth_request off;")
        lines.append(f"    proxy_pass {proxy_base}/oauth2/;")
        lines.append("    proxy_set_header Host $host;")
        lines.append("    proxy_set_header X-Real-IP $remote_addr;")
        lines.append("    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
        lines.append("    proxy_set_header X-Forwarded-Proto $scheme;")
        lines.append("    proxy_set_header X-Forwarded-Host $host;")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def generate_nginx_apps_conf(db: Session) -> str:
    """Proxy vhosts only — sso_gate apps are catalogue entries without nginx proxy."""
    from app.access_modes import PROXY_ACCESS_MODES, normalize_access_mode
    from app.models import App

    apps = db.query(App).filter_by(enabled=True).order_by(App.slug).all()
    lines = [
        "# Generated by bastion-app — application proxy snippets",
        "# sso_gate entries are catalogue-only (no proxy block below).",
        "",
    ]

    for app in apps:
        mode = normalize_access_mode(app.access_mode)
        if mode not in PROXY_ACCESS_MODES:
            lines.append(f"# [{app.slug}] SSO Gate — {app.upstream_url}")
            lines.append("")
            continue

        if mode == "subdomain_proxy" and app.public_fqdn:
            lines.append(f"# [{app.slug}] subdomain_proxy — {app.public_fqdn}")
            lines.append("server {")
            lines.append(f"    server_name {app.public_fqdn.strip()};")
            lines.append(f"    # proxy_pass {app.upstream_url};")
            lines.append("    # include snippets/subdomain_auth_common.conf;")
            lines.append("}")
            lines.append("")
        elif mode == "legacy_path_proxy":
            lines.append(f"# [{app.slug}] legacy_path_proxy")
            lines.append(f"location /proxy/{app.slug}/ {{")
            lines.append(f"    proxy_pass {app.upstream_url};")
            lines.append("    # auth_request /internal/oauth2-auth;")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def export_app_catalogue_files(db: Session, settings: Settings) -> dict[str, str]:
    exports_path = _exports_path(settings)
    apps_path = exports_path / "nginx-portal-apps.conf"
    apps_path.write_text(generate_nginx_apps_conf(db), encoding="utf-8")
    return {"nginx_apps_conf": str(apps_path)}


def write_oauth2_proxy_export(realm: RealmConfig, settings: Settings) -> Path:
    """Write flat + nested oauth2 configs (bare-metal apply + docker apply-infra)."""
    exports_path = _exports_path(settings)
    content = generate_oauth2_proxy_config(realm, settings)
    flat_path = exports_path / f"oauth2-proxy-{realm.slug}.conf"
    flat_path.write_text(content, encoding="utf-8")
    nested_dir = exports_path / "oauth2" / realm.slug
    nested_dir.mkdir(parents=True, exist_ok=True)
    (nested_dir / "oauth2-proxy.cfg").write_text(content, encoding="utf-8")
    return flat_path


def write_nginx_realms_conf(db: Session, settings: Settings) -> Path:
    """Rewrite nginx-portal-realms.conf from current enabled realms in DB."""
    exports_path = _exports_path(settings)
    nginx_path = exports_path / "nginx-portal-realms.conf"
    nginx_path.write_text(
        generate_nginx_realms_conf(
            db, settings, exclude_slugs=core_static_realm_slugs(settings)
        ),
        encoding="utf-8",
    )
    return nginx_path


def export_realm_files(realm: RealmConfig, db: Session, settings: Settings) -> dict[str, str]:
    proxy_config_path = write_oauth2_proxy_export(realm, settings)
    nginx_path = write_nginx_realms_conf(db, settings)
    return {
        "oauth2_proxy_config": str(proxy_config_path),
        "nginx_realms_conf": str(nginx_path),
    }


# Marker consumed by scripts/apply-infrastructure.sh — one unit basename per line.
SYSTEMD_PURGE_LIST_NAME = "purge-units.list"


def oauth2_proxy_systemd_unit_name(slug: str) -> str:
    return f"oauth2-proxy-portal-{slug}.service"


def record_systemd_unit_purge(slug: str, settings: Settings) -> Path:
    """Append a systemd unit to the purge list for the next AWX/apply run.

    apply-infrastructure.sh installs units from exports/systemd/*.service when present;
    there is no reverse format yet, so we write an explicit purge-units.list marker
    (unit basenames) rather than inventing a fake .service file.
    """
    exports_path = _exports_path(settings)
    systemd_dir = exports_path / "systemd"
    systemd_dir.mkdir(parents=True, exist_ok=True)

    unit_name = oauth2_proxy_systemd_unit_name(slug)
    # Drop any previously exported install unit so apply won't re-install it.
    (systemd_dir / unit_name).unlink(missing_ok=True)

    purge_list = systemd_dir / SYSTEMD_PURGE_LIST_NAME
    existing: set[str] = set()
    if purge_list.is_file():
        existing = {
            line.strip()
            for line in purge_list.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        }
    existing.add(unit_name)
    lines = [
        "# Generated by bastion-app — units to disable/remove on next apply-infrastructure.sh run",
        *sorted(existing),
        "",
    ]
    purge_list.write_text("\n".join(lines), encoding="utf-8")
    return purge_list


def prune_deleted_realm_exports(db: Session, settings: Settings) -> dict[str, list[str]]:
    """Remove oauth2-proxy config files for realms that no longer exist in DB.

    This enables "purge on delete" without directly touching systemd/nginx. AWX/Ansible
    can reconcile based on export dir contents.
    """
    exports_path = _exports_path(settings)
    existing_slugs = {slug for (slug,) in db.query(RealmConfig.slug).all() if slug}
    removed: list[str] = []
    for path in exports_path.glob("oauth2-proxy-*.conf"):
        slug = path.stem.removeprefix("oauth2-proxy-")
        if slug and slug not in existing_slugs:
            try:
                path.unlink(missing_ok=True)
                removed.append(str(path))
            except OSError:
                # best-effort; keep going
                continue
    oauth2_root = exports_path / "oauth2"
    if oauth2_root.is_dir():
        for slug_dir in oauth2_root.iterdir():
            if not slug_dir.is_dir():
                continue
            if slug_dir.name in existing_slugs:
                continue
            try:
                for child in slug_dir.iterdir():
                    child.unlink(missing_ok=True)
                slug_dir.rmdir()
                removed.append(str(slug_dir))
            except OSError:
                continue
    return {"removed": removed}


def purge_realm_exports_after_delete(
    db: Session, settings: Settings, *, deleted_slug: str
) -> dict[str, str | list[str]]:
    """Full export purge after a realm row was deleted: oauth2 files, nginx rewrite, systemd marker."""
    pruned = prune_deleted_realm_exports(db, settings)
    nginx_path = write_nginx_realms_conf(db, settings)
    purge_list = record_systemd_unit_purge(deleted_slug, settings)
    return {
        "removed": pruned.get("removed", []),
        "nginx_realms_conf": str(nginx_path),
        "systemd_purge_list": str(purge_list),
        "systemd_unit": oauth2_proxy_systemd_unit_name(deleted_slug),
    }


def persist_test_result(realm: RealmConfig, result: dict) -> None:
    realm.last_test_status = result["status"]
    realm.last_test_detail = json.dumps(result, ensure_ascii=False)
    from app.models import utcnow

    realm.last_tested_at = utcnow()
