# public_proxy family
Include /etc/nginx/modsecurity/engine-public.conf
Include /etc/nginx/modsecurity/modsecurity.conf
Include /etc/nginx/modsecurity/crs-setup.conf
Include /etc/nginx/modsecurity/generated/crs-setup-generated.conf
Include /etc/modsecurity.d/owasp-crs/rules/*.conf
Include /etc/nginx/includes/waf-basic.conf
Include /etc/nginx/modsecurity/generated/bastion-exclusions-generated.conf
Include /etc/nginx/modsecurity/generated/engine-mode-generated.conf
