# Portal family — rules file referenced by vhost_sso_portal
Include /etc/nginx/modsecurity/engine-portal.conf
Include /etc/nginx/modsecurity/modsecurity.conf
Include /etc/nginx/modsecurity/crs-setup.conf
Include /etc/modsecurity.d/owasp-crs/rules/*.conf
Include /etc/nginx/includes/waf-basic.conf
