#!/usr/bin/env bash
# Render snippets that need secrets, then start nginx.
set -euo pipefail

export PORTAL_INTERNAL_TOKEN="${PORTAL_INTERNAL_TOKEN:-}"
export PORTAL_DOMAIN="${PORTAL_DOMAIN:-portal.ar-systems.fr}"
export SSO_PORTAL_DEFAULT_REALM_SLUG="${SSO_PORTAL_DEFAULT_REALM_SLUG:-ar-systems}"

if [[ -z "${PORTAL_INTERNAL_TOKEN}" ]]; then
  echo "WARN: PORTAL_INTERNAL_TOKEN empty — FastAPI internal auth may fail" >&2
fi

# Ensure exports include exists (empty stub if missing).
# exports/ is often :ro in the nginx container — only write when the FS allows it.
mkdir -p /var/lib/sso-portal/exports 2>/dev/null || true
if [[ ! -f /var/lib/sso-portal/exports/nginx-portal-realms.conf ]]; then
  echo "# no secondary realms yet" > /var/lib/sso-portal/exports/nginx-portal-realms.conf 2>/dev/null \
    || echo "WARN: exports/nginx-portal-realms.conf missing and exports is read-only" >&2
fi

# Subdomain apps (from App DB via infrastructure apply) — product-agnostic hop included
if [[ -f /var/lib/sso-portal/exports/nginx-subdomain-apps.conf ]]; then
  cp -a /var/lib/sso-portal/exports/nginx-subdomain-apps.conf \
    /etc/nginx/conf.d/nginx-subdomain-apps.conf
else
  echo "# no subdomain_proxy apps exported yet" > /etc/nginx/conf.d/nginx-subdomain-apps.conf
fi

# Public proxy apps (no bastion auth) — separate file from subdomain_proxy
if [[ -f /var/lib/sso-portal/exports/nginx-public-proxy-apps.conf ]]; then
  cp -a /var/lib/sso-portal/exports/nginx-public-proxy-apps.conf \
    /etc/nginx/conf.d/nginx-public-proxy-apps.conf
else
  echo "# no public_proxy apps exported yet" > /etc/nginx/conf.d/nginx-public-proxy-apps.conf
fi

# Infra proxies (Keycloak, Grafana, …) — static list from Ansible exports
if [[ -f /var/lib/sso-portal/exports/nginx-infra-proxy-apps.conf ]]; then
  cp -a /var/lib/sso-portal/exports/nginx-infra-proxy-apps.conf \
    /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
else
  echo "# no infra proxy vhosts exported yet" > /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
fi

# Known Hosts map for unknown-Host discovery.
# exports/ is mounted :ro — never write there. Defaults only go into conf.d.
# Map body from bastion-app (export_app_catalogue_files) is optional on first boot.
# BASTION_KNOWN_HOSTS_DEDUPE=1 — nginx map rejects duplicate hostnames.
MAP_SRC=/var/lib/sso-portal/exports/nginx-known-hosts.map
{
  echo "# Regenerated by docker-entrypoint — do not edit"
  echo "map \$host \$bastion_unknown_host {"
  echo "    default 1;"
  {
    echo "127.0.0.1 0;"
    echo "localhost 0;"
    echo "${PORTAL_DOMAIN} 0;"
    if [[ -f "$MAP_SRC" ]]; then
      grep -E '^[A-Za-z0-9][A-Za-z0-9.-]*[[:space:]]+0[[:space:]]*;[[:space:]]*$' "$MAP_SRC" || true
    fi
  } | awk 'NF >= 2 && !seen[$1]++ { printf "    %s %s\n", $1, $2 }'
  echo "}"
} > /etc/nginx/conf.d/00-known-hosts-map.conf

envsubst '${PORTAL_INTERNAL_TOKEN}' \
  < /etc/nginx/templates-portal/proxy_portal_trusted_internal.conf.template \
  > /etc/nginx/snippets/proxy_portal_trusted_internal.conf

envsubst '${PORTAL_DOMAIN} ${SSO_PORTAL_DEFAULT_REALM_SLUG}' \
  < /etc/nginx/templates-portal/vhost_sso_portal.conf.template \
  > /etc/nginx/conf.d/vhost_sso_portal.conf

# Fail fast if vhost render did not produce a listener (avoids "running" with no :8080)
if ! grep -qE 'listen[[:space:]]+0\.0\.0\.0:8080([[:space:]]+default_server)?' \
  /etc/nginx/conf.d/vhost_sso_portal.conf; then
  echo "ERROR: rendered vhost missing listen 0.0.0.0:8080" >&2
  cat /etc/nginx/conf.d/vhost_sso_portal.conf >&2 || true
  exit 1
fi
if ! grep -qE 'listen[[:space:]]+0\.0\.0\.0:8080[[:space:]]+default_server' \
  /etc/nginx/conf.d/vhost_sso_portal.conf; then
  echo "ERROR: portal vhost must be default_server on :8080 (else subdomain/public_proxy steal loopback health)" >&2
  exit 1
fi

nginx -t
exec "$@"
