#!/usr/bin/env bash
# Render snippets that need secrets, then start nginx.
set -euo pipefail

export PORTAL_INTERNAL_TOKEN="${PORTAL_INTERNAL_TOKEN:-}"
export PORTAL_DOMAIN="${PORTAL_DOMAIN:-portal.ar-systems.fr}"
export SSO_PORTAL_DEFAULT_REALM_SLUG="${SSO_PORTAL_DEFAULT_REALM_SLUG:-ar-systems}"

if [[ -z "${PORTAL_INTERNAL_TOKEN}" ]]; then
  echo "WARN: PORTAL_INTERNAL_TOKEN empty — FastAPI internal auth may fail" >&2
fi

# Ensure exports include exists (empty stub if missing)
mkdir -p /var/lib/sso-portal/exports
if [[ ! -f /var/lib/sso-portal/exports/nginx-portal-realms.conf ]]; then
  echo "# no secondary realms yet" > /var/lib/sso-portal/exports/nginx-portal-realms.conf
fi

# Subdomain apps (from App DB via infrastructure apply) — product-agnostic hop included
if [[ -f /var/lib/sso-portal/exports/nginx-subdomain-apps.conf ]]; then
  cp -a /var/lib/sso-portal/exports/nginx-subdomain-apps.conf \
    /etc/nginx/conf.d/nginx-subdomain-apps.conf
else
  echo "# no subdomain_proxy apps exported yet" > /etc/nginx/conf.d/nginx-subdomain-apps.conf
fi

# Public proxy apps (no bastion auth) — separate file from subdomain_proxy
if [[ -f /var/lib/sso-portal/exports/nginx-public-proxy-apps.conf ]]; then
  cp -a /var/lib/sso-portal/exports/nginx-public-proxy-apps.conf \
    /etc/nginx/conf.d/nginx-public-proxy-apps.conf
else
  echo "# no public_proxy apps exported yet" > /etc/nginx/conf.d/nginx-public-proxy-apps.conf
fi

# Infra proxies (Keycloak, Grafana, …) — static list from Ansible exports
if [[ -f /var/lib/sso-portal/exports/nginx-infra-proxy-apps.conf ]]; then
  cp -a /var/lib/sso-portal/exports/nginx-infra-proxy-apps.conf \
    /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
else
  echo "# no infra proxy vhosts exported yet" > /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
fi

# Known Hosts map (unknown-Host discovery). Always present so nginx -t succeeds.
if [[ ! -f /var/lib/sso-portal/exports/nginx-known-hosts.map ]]; then
  {
    echo "# stub — regenerated by Admin apply / export_app_catalogue_files"
    echo "127.0.0.1 0;"
    echo "localhost 0;"
    echo "${PORTAL_DOMAIN} 0;"
  } > /var/lib/sso-portal/exports/nginx-known-hosts.map
fi
cat > /etc/nginx/conf.d/00-known-hosts-map.conf <<'EOF'
# Generated at container start — do not edit; map body comes from exports.
map $host $bastion_unknown_host {
    default 1;
    include /var/lib/sso-portal/exports/nginx-known-hosts.map;
}
EOF

envsubst '${PORTAL_INTERNAL_TOKEN}' \
  < /etc/nginx/templates-portal/proxy_portal_trusted_internal.conf.template \
  > /etc/nginx/snippets/proxy_portal_trusted_internal.conf

envsubst '${PORTAL_DOMAIN} ${SSO_PORTAL_DEFAULT_REALM_SLUG}' \
  < /etc/nginx/templates-portal/vhost_sso_portal.conf.template \
  > /etc/nginx/conf.d/vhost_sso_portal.conf

# Fail fast if vhost render did not produce a listener (avoids "running" with no :8080)
if ! grep -qE 'listen[[:space:]]+0\.0\.0\.0:8080([[:space:]]+default_server)?' \
  /etc/nginx/conf.d/vhost_sso_portal.conf; then
  echo "ERROR: rendered vhost missing listen 0.0.0.0:8080" >&2
  cat /etc/nginx/conf.d/vhost_sso_portal.conf >&2 || true
  exit 1
fi
if ! grep -qE 'listen[[:space:]]+0\.0\.0\.0:8080[[:space:]]+default_server' \
  /etc/nginx/conf.d/vhost_sso_portal.conf; then
  echo "ERROR: portal vhost must be default_server on :8080 (else subdomain/public_proxy steal loopback health)" >&2
  exit 1
fi

nginx -t
exec "$@"
