#!/usr/bin/env bash
# TLS :443 for every ACME-covered FQDN (portal / subdomain_proxy / public_proxy)
# + HTTP :80 → 301 HTTPS. Terminates TLS then proxies to local :8080.
set -euo pipefail

EXPORTS="${EXPORTS_DIR:-/var/lib/sso-portal/exports}"
CERTS="${CERTS_DIR:-/etc/nginx/ssl}"
OUT="/etc/nginx/conf.d/nginx-acme-tls.conf"
LEGACY_OUT="/etc/nginx/conf.d/nginx-public-proxy-apps-tls.conf"
MANIFEST="${EXPORTS}/acme-domains.json"
LOCAL_SSL="/etc/nginx/ssl-local"
DEFAULT_CERT="${LOCAL_SSL}/_default/fullchain.pem"
DEFAULT_KEY="${LOCAL_SSL}/_default/privkey.pem"

mkdir -p /var/log/nginx/apps "$LOCAL_SSL/_default"

ensure_default_cert() {
  if [[ -f "$DEFAULT_CERT" && -f "$DEFAULT_KEY" ]]; then
    return 0
  fi
  if ! command -v openssl >/dev/null 2>&1; then
    echo "WARN: openssl missing — cannot bootstrap default TLS cert" >&2
    return 1
  fi
  openssl req -x509 -nodes -newkey rsa:2048 -days 30 \
    -keyout "$DEFAULT_KEY" \
    -out "$DEFAULT_CERT" \
    -subj "/CN=bastion-default" 2>/dev/null
}

ensure_default_cert || true

{
  echo "# Generated by sync-acme-tls.sh — do not edit"
  echo "# listen 80 → 301 https://\$host\$request_uri ; listen 443 ssl → :8080"
  echo ""
  echo "# HTTP → HTTPS (edge nginx, no Traefik)"
  echo "server {"
  echo "    listen 0.0.0.0:80 default_server;"
  echo "    listen [::]:80 default_server;"
  echo "    server_name _;"
  echo "    return 301 https://\$host\$request_uri;"
  echo "}"
  echo ""
} > "$OUT"

if [[ -f "$DEFAULT_CERT" && -f "$DEFAULT_KEY" ]]; then
  cat >> "$OUT" <<EOF
# Default HTTPS (unknown SNI / bootstrap before ACME)
server {
    listen 0.0.0.0:443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl_certificate     ${DEFAULT_CERT};
    ssl_certificate_key ${DEFAULT_KEY};
    ssl_protocols TLSv1.2 TLSv1.3;

    absolute_redirect off;
    port_in_redirect off;

    location = /_portal_nginx_ok {
        proxy_pass http://127.0.0.1:8080/_portal_nginx_ok;
        proxy_set_header Host \$host;
    }

    location / {
        return 503;
    }
}

EOF
fi

if [[ ! -f "$MANIFEST" ]]; then
  echo "# (no acme-domains.json yet)" >> "$OUT"
  cp -a "$OUT" "$LEGACY_OUT"
  exit 0
fi

emit_rows() {
  if command -v jq >/dev/null 2>&1; then
    jq -r '.domains[] | [.fqdn, .slug, (.family // "app")] | @tsv' "$MANIFEST"
  else
    grep -oE '"fqdn"[[:space:]]*:[[:space:]]*"[^"]+"' "$MANIFEST" \
      | sed 's/.*"\([^"]*\)"$/\1/' \
      | while read -r f; do
          printf '%s\t%s\t%s\n' "$f" "${f%%.*}" "app"
        done
  fi
}

while IFS=$'\t' read -r fqdn slug family; do
  [[ -n "${fqdn:-}" ]] || continue
  cert="$CERTS/$fqdn/fullchain.pem"
  key="$CERTS/$fqdn/privkey.pem"
  if [[ ! -f "$cert" || ! -f "$key" ]]; then
    echo "# skip $fqdn — certs not ready" >> "$OUT"
    continue
  fi
  slug="${slug:-app}"
  family="${family:-app}"
  fqdn_esc="${fqdn//\\/\\\\}"
  fqdn_esc="${fqdn_esc//\"/\\\"}"

  cat >> "$OUT" <<EOF
# [${slug}] ${family} TLS terminator — ${fqdn}
server {
    listen 0.0.0.0:443 ssl;
    listen [::]:443 ssl;
    server_name ${fqdn_esc};

    ssl_certificate     ${cert};
    ssl_certificate_key ${key};
    ssl_protocols TLSv1.2 TLSv1.3;

    absolute_redirect off;
    port_in_redirect off;

    access_log /var/log/nginx/apps/${slug}.access.log app;
    error_log  /var/log/nginx/apps/${slug}.error.log warn;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port 443;
    }
}

EOF
done < <(emit_rows)

cp -a "$OUT" "$LEGACY_OUT"
