#!/usr/bin/env bash
# Build nginx TLS server{} blocks for public_proxy FQDNs that have certs under /etc/nginx/ssl.
# HTTP :8080 blocks stay in nginx-public-proxy-apps.conf; this file only adds :8443 ssl.
set -euo pipefail

EXPORTS="${EXPORTS_DIR:-/var/lib/sso-portal/exports}"
CERTS="${CERTS_DIR:-/etc/nginx/ssl}"
OUT="/etc/nginx/conf.d/nginx-public-proxy-apps-tls.conf"
MANIFEST="${EXPORTS}/acme-domains.json"

mkdir -p /var/log/nginx/apps

{
  echo "# Generated by sync-public-proxy-tls.sh — do not edit"
  echo "# TLS listen 8443 for public_proxy when certs exist under ${CERTS}/<fqdn>/"
  echo ""
} > "$OUT"

if [[ ! -f "$MANIFEST" ]]; then
  echo "# (no acme-domains.json yet)" >> "$OUT"
  exit 0
fi

emit_rows() {
  if command -v jq >/dev/null 2>&1; then
    jq -r '.domains[] | [.fqdn, .slug, (.upstream_url // "https://127.0.0.1/")] | @tsv' "$MANIFEST"
  else
    grep -oE '"fqdn"[[:space:]]*:[[:space:]]*"[^"]+"' "$MANIFEST" \
      | sed 's/.*"\([^"]*\)"$/\1/' \
      | while read -r f; do
          printf '%s\t%s\t%s\n' "$f" "${f%%.*}" "https://127.0.0.1/"
        done
  fi
}

while IFS=$'\t' read -r fqdn slug upstream; do
  [[ -n "${fqdn:-}" ]] || continue
  cert="$CERTS/$fqdn/fullchain.pem"
  key="$CERTS/$fqdn/privkey.pem"
  if [[ ! -f "$cert" || ! -f "$key" ]]; then
    echo "# skip $fqdn — certs not ready" >> "$OUT"
    continue
  fi
  upstream="${upstream%/}"
  slug="${slug:-app}"
  fqdn_esc="${fqdn//\\/\\\\}"
  fqdn_esc="${fqdn_esc//\"/\\\"}"
  up_esc="${upstream//\\/\\\\}"
  up_esc="${up_esc//\"/\\\"}"

  cat >> "$OUT" <<EOF
# [${slug}] public_proxy TLS — ${fqdn}
server {
    listen 0.0.0.0:8443 ssl;
    server_name ${fqdn_esc};

    ssl_certificate     ${cert};
    ssl_certificate_key ${key};
    ssl_protocols TLSv1.2 TLSv1.3;

    absolute_redirect off;
    port_in_redirect off;

    access_log /var/log/nginx/apps/${slug}.access.log app;
    error_log  /var/log/nginx/apps/${slug}.error.log warn;

    set \$app_upstream "${up_esc}";

    location = /healthz {
        access_log off;
        proxy_pass \$app_upstream/;
        proxy_redirect off;
        proxy_set_header Host \$host;
    }

    location / {
        proxy_pass \$app_upstream;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
    }
}

EOF
done < <(emit_rows)
