#!/usr/bin/env bash
# Copy App DB nginx exports into conf.d and rebuild the known-hosts map.
# Safe to call at start (entrypoint) and whenever exports/ change (watcher).
set -euo pipefail

EXPORTS="${EXPORTS_DIR:-/var/lib/sso-portal/exports}"
PORTAL_DOMAIN_EFF="${PORTAL_DOMAIN:-portal.ar-systems.fr}"

mkdir -p /var/log/nginx/apps
# Shared bind-mount with bastion-app (Admin → Logs → Accès apps). Ensure writable
# even when Docker created the host dir as root:root.
chmod 0777 /var/log/nginx/apps 2>/dev/null || true
if ! touch /var/log/nginx/apps/.bastion-write-ok 2>/dev/null; then
  echo "WARN: /var/log/nginx/apps not writable — Accès apps will stay empty" >&2
else
  rm -f /var/log/nginx/apps/.bastion-write-ok 2>/dev/null || true
fi

if [[ -f "$EXPORTS/nginx-subdomain-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-subdomain-apps.conf" \
    /etc/nginx/conf.d/nginx-subdomain-apps.conf
else
  echo "# no subdomain_proxy apps exported yet" > /etc/nginx/conf.d/nginx-subdomain-apps.conf
fi

if [[ -f "$EXPORTS/nginx-public-proxy-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-public-proxy-apps.conf" \
    /etc/nginx/conf.d/nginx-public-proxy-apps.conf
else
  echo "# no public_proxy apps exported yet" > /etc/nginx/conf.d/nginx-public-proxy-apps.conf
fi

if [[ -f "$EXPORTS/nginx-infra-proxy-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-infra-proxy-apps.conf" \
    /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
else
  echo "# no infra proxy vhosts exported yet" > /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
fi

# exports/ is often :ro — never write MAP_SRC; only regenerate conf.d map.
# BASTION_KNOWN_HOSTS_DEDUPE=1
MAP_SRC="$EXPORTS/nginx-known-hosts.map"
{
  echo "# Regenerated by sync-exports-to-confd.sh — do not edit"
  echo "map \$host \$bastion_unknown_host {"
  echo "    default 1;"
  {
    echo "127.0.0.1 0;"
    echo "localhost 0;"
    echo "${PORTAL_DOMAIN_EFF} 0;"
    if [[ -f "$MAP_SRC" ]]; then
      grep -E '^[A-Za-z0-9][A-Za-z0-9.-]*[[:space:]]+0[[:space:]]*;[[:space:]]*$' "$MAP_SRC" || true
    fi
  } | awk 'NF >= 2 && !seen[$1]++ { printf "    %s %s\n", $1, $2 }'
  echo "}"
} > /etc/nginx/conf.d/00-known-hosts-map.conf

# TLS :443 for all ACME domains (portal / subdomain / public_proxy) when certs exist
# + HTTP :80 → 301 HTTPS
if [[ -x /sync-acme-tls.sh ]]; then
  /sync-acme-tls.sh || echo "WARN: sync-acme-tls failed" >&2
elif [[ -x /sync-public-proxy-tls.sh ]]; then
  /sync-public-proxy-tls.sh || echo "WARN: sync-public-proxy-tls failed" >&2
else
  echo "# no ACME TLS sync script" > /etc/nginx/conf.d/nginx-acme-tls.conf
  echo "# deprecated — see nginx-acme-tls.conf" > /etc/nginx/conf.d/nginx-public-proxy-apps-tls.conf
fi

# --- WAF Phase B overlays (never overwrite Phase A static crs-setup / waf-basic / engine-*) ---
mkdir -p /etc/nginx/modsecurity/generated
if [[ -f "$EXPORTS/modsecurity/crs-setup-generated.conf" ]]; then
  # Stale exports may still use id:901110 (CRS REQUEST-901 collision → HTTP 500 on every
  # ModSec-enabled request). Rewrite on install so a bad volume cannot brick the portal.
  sed 's/id:901110,/id:1000900110,/g' \
    "$EXPORTS/modsecurity/crs-setup-generated.conf" \
    > /etc/nginx/modsecurity/generated/crs-setup-generated.conf
  if grep -qE 'id:901[0-9]{3},' /etc/nginx/modsecurity/generated/crs-setup-generated.conf; then
    echo "WARN: crs-setup-generated export still uses CRS 901xxx id — refusing, keeping safe default" >&2
    cat > /etc/nginx/modsecurity/generated/crs-setup-generated.conf <<'EOF'
# Refused unsafe export (CRS 901xxx rule id). Thresholds: Admin → WAF after bastion-app upgrade.
SecAction \
    "id:1000900110,\
    phase:1,\
    nolog,\
    pass,\
    t:none,\
    setvar:tx.inbound_anomaly_score_threshold=5,\
    setvar:tx.outbound_anomaly_score_threshold=4"
EOF
  fi
fi
if [[ -f "$EXPORTS/modsecurity/engine-mode-generated.conf" ]]; then
  cp -a "$EXPORTS/modsecurity/engine-mode-generated.conf" \
    /etc/nginx/modsecurity/generated/engine-mode-generated.conf
fi
if [[ -f "$EXPORTS/modsecurity/bastion-exclusions-generated.conf" ]]; then
  cp -a "$EXPORTS/modsecurity/bastion-exclusions-generated.conf" \
    /etc/nginx/modsecurity/generated/bastion-exclusions-generated.conf
fi
if [[ -f "$EXPORTS/waf-ip-deny.conf" ]]; then
  cp -a "$EXPORTS/waf-ip-deny.conf" /etc/nginx/includes/waf-ip-deny.conf
fi
if [[ -f "$EXPORTS/nginx-portal-rate-limits.conf" ]]; then
  cp -a "$EXPORTS/nginx-portal-rate-limits.conf" \
    /etc/nginx/includes/nginx-portal-rate-limits.conf
fi
