#!/usr/bin/env bash
# Copy App DB nginx exports into conf.d and rebuild the known-hosts map.
# Safe to call at start (entrypoint) and whenever exports/ change (watcher).
set -euo pipefail

EXPORTS="${EXPORTS_DIR:-/var/lib/sso-portal/exports}"
PORTAL_DOMAIN_EFF="${PORTAL_DOMAIN:-portal.ar-systems.fr}"

mkdir -p /var/log/nginx/apps
# Shared bind-mount with bastion-app (Admin → Logs → Accès apps). Ensure writable
# even when Docker created the host dir as root:root.
chmod 0777 /var/log/nginx/apps 2>/dev/null || true
if ! touch /var/log/nginx/apps/.bastion-write-ok 2>/dev/null; then
  echo "WARN: /var/log/nginx/apps not writable — Accès apps will stay empty" >&2
else
  rm -f /var/log/nginx/apps/.bastion-write-ok 2>/dev/null || true
fi

if [[ -f "$EXPORTS/nginx-subdomain-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-subdomain-apps.conf" \
    /etc/nginx/conf.d/nginx-subdomain-apps.conf
else
  echo "# no subdomain_proxy apps exported yet" > /etc/nginx/conf.d/nginx-subdomain-apps.conf
fi

if [[ -f "$EXPORTS/nginx-public-proxy-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-public-proxy-apps.conf" \
    /etc/nginx/conf.d/nginx-public-proxy-apps.conf
else
  echo "# no public_proxy apps exported yet" > /etc/nginx/conf.d/nginx-public-proxy-apps.conf
fi

if [[ -f "$EXPORTS/nginx-infra-proxy-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-infra-proxy-apps.conf" \
    /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
else
  echo "# no infra proxy vhosts exported yet" > /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
fi

# exports/ is often :ro — never write MAP_SRC; only regenerate conf.d map.
# BASTION_KNOWN_HOSTS_DEDUPE=1
MAP_SRC="$EXPORTS/nginx-known-hosts.map"
{
  echo "# Regenerated by sync-exports-to-confd.sh — do not edit"
  echo "map \$host \$bastion_unknown_host {"
  echo "    default 1;"
  {
    echo "127.0.0.1 0;"
    echo "localhost 0;"
    echo "${PORTAL_DOMAIN_EFF} 0;"
    if [[ -f "$MAP_SRC" ]]; then
      grep -E '^[A-Za-z0-9][A-Za-z0-9.-]*[[:space:]]+0[[:space:]]*;[[:space:]]*$' "$MAP_SRC" || true
    fi
  } | awk 'NF >= 2 && !seen[$1]++ { printf "    %s %s\n", $1, $2 }'
  echo "}"
} > /etc/nginx/conf.d/00-known-hosts-map.conf

# TLS :443 for all ACME domains (portal / subdomain / public_proxy) when certs exist
# + HTTP :80 → 301 HTTPS
if [[ -x /sync-acme-tls.sh ]]; then
  /sync-acme-tls.sh || echo "WARN: sync-acme-tls failed" >&2
elif [[ -x /sync-public-proxy-tls.sh ]]; then
  /sync-public-proxy-tls.sh || echo "WARN: sync-public-proxy-tls failed" >&2
else
  echo "# no ACME TLS sync script" > /etc/nginx/conf.d/nginx-acme-tls.conf
  echo "# deprecated — see nginx-acme-tls.conf" > /etc/nginx/conf.d/nginx-public-proxy-apps-tls.conf
fi

# --- WAF Phase B overlays (never overwrite Phase A static crs-setup / waf-basic / engine-*) ---
mkdir -p /etc/nginx/modsecurity/generated
# crs-setup-generated.conf is NOT Included by main-*.conf (stale id:901110 → HTTP 500).
# Still sanitize the on-disk export + image copy so a future re-Include cannot brick prod.
if [[ -f "$EXPORTS/modsecurity/crs-setup-generated.conf" ]]; then
  if grep -qE 'id:901[0-9]{3},' "$EXPORTS/modsecurity/crs-setup-generated.conf" 2>/dev/null; then
    echo "WARN: sanitizing exports/modsecurity/crs-setup-generated.conf (CRS 901xxx rule id)" >&2
    sed -i 's/id:901110,/id:1000900110,/g' "$EXPORTS/modsecurity/crs-setup-generated.conf" || true
  fi
fi
# Keep generated copy as comment-only stub (not loaded). Thresholds = static crs-setup.conf.
cat > /etc/nginx/modsecurity/generated/crs-setup-generated.conf <<'EOF'
# Not loaded by main-*.conf — anomaly thresholds come from ../crs-setup.conf (id:900110).
# Export may still be written by Admin → WAF for a future safe re-Include (id:1000900110).
EOF

# Portal ModSecurity connector switch (IHM reactivation / rollback).
if [[ -f "$EXPORTS/modsecurity-portal-switch.conf" ]]; then
  cp -a "$EXPORTS/modsecurity-portal-switch.conf" \
    /etc/nginx/includes/modsecurity-portal-switch.conf
else
  cat > /etc/nginx/includes/modsecurity-portal-switch.conf <<'EOF'
# Default safe state — no export yet.
modsecurity off;
EOF
fi

# Engine mode overlay: copy export only when IHM armed (waf-engine-arm.json).
# Otherwise force Off so a DB profile mode=on cannot brick the edge.
ARMED=0
if [[ -f "$EXPORTS/modsecurity/waf-engine-arm.json" ]]; then
  if grep -Eq '"armed"[[:space:]]*:[[:space:]]*true' "$EXPORTS/modsecurity/waf-engine-arm.json" 2>/dev/null; then
    ARMED=1
  fi
fi
if [[ "$ARMED" -eq 1 && -f "$EXPORTS/modsecurity/engine-mode-generated.conf" ]]; then
  cp -a "$EXPORTS/modsecurity/engine-mode-generated.conf" \
    /etc/nginx/modsecurity/generated/engine-mode-generated.conf
else
  cat > /etc/nginx/modsecurity/generated/engine-mode-generated.conf <<'EOF'
# Not armed — IHM must run Réactiver (DetectionOnly + smoke). See waf_reactivation.
SecRuleEngine Off
EOF
fi

if [[ -f "$EXPORTS/modsecurity/bastion-exclusions-generated.conf" ]]; then
  cp -a "$EXPORTS/modsecurity/bastion-exclusions-generated.conf" \
    /etc/nginx/modsecurity/generated/bastion-exclusions-generated.conf
fi
if [[ -f "$EXPORTS/waf-ip-deny.conf" ]]; then
  cp -a "$EXPORTS/waf-ip-deny.conf" /etc/nginx/includes/waf-ip-deny.conf
fi
if [[ -f "$EXPORTS/nginx-portal-rate-limits.conf" ]]; then
  cp -a "$EXPORTS/nginx-portal-rate-limits.conf" \
    /etc/nginx/includes/nginx-portal-rate-limits.conf
fi
