#!/usr/bin/env bash
# Copy App DB nginx exports into conf.d and rebuild the known-hosts map.
# Safe to call at start (entrypoint) and whenever exports/ change (watcher).
set -euo pipefail

EXPORTS="${EXPORTS_DIR:-/var/lib/sso-portal/exports}"
PORTAL_DOMAIN_EFF="${PORTAL_DOMAIN:-portal.ar-systems.fr}"

mkdir -p /var/log/nginx/apps

if [[ -f "$EXPORTS/nginx-subdomain-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-subdomain-apps.conf" \
    /etc/nginx/conf.d/nginx-subdomain-apps.conf
else
  echo "# no subdomain_proxy apps exported yet" > /etc/nginx/conf.d/nginx-subdomain-apps.conf
fi

if [[ -f "$EXPORTS/nginx-public-proxy-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-public-proxy-apps.conf" \
    /etc/nginx/conf.d/nginx-public-proxy-apps.conf
else
  echo "# no public_proxy apps exported yet" > /etc/nginx/conf.d/nginx-public-proxy-apps.conf
fi

if [[ -f "$EXPORTS/nginx-infra-proxy-apps.conf" ]]; then
  cp -a "$EXPORTS/nginx-infra-proxy-apps.conf" \
    /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
else
  echo "# no infra proxy vhosts exported yet" > /etc/nginx/conf.d/nginx-infra-proxy-apps.conf
fi

# exports/ is often :ro — never write MAP_SRC; only regenerate conf.d map.
# BASTION_KNOWN_HOSTS_DEDUPE=1
MAP_SRC="$EXPORTS/nginx-known-hosts.map"
{
  echo "# Regenerated by sync-exports-to-confd.sh — do not edit"
  echo "map \$host \$bastion_unknown_host {"
  echo "    default 1;"
  {
    echo "127.0.0.1 0;"
    echo "localhost 0;"
    echo "${PORTAL_DOMAIN_EFF} 0;"
    if [[ -f "$MAP_SRC" ]]; then
      grep -E '^[A-Za-z0-9][A-Za-z0-9.-]*[[:space:]]+0[[:space:]]*;[[:space:]]*$' "$MAP_SRC" || true
    fi
  } | awk 'NF >= 2 && !seen[$1]++ { printf "    %s %s\n", $1, $2 }'
  echo "}"
} > /etc/nginx/conf.d/00-known-hosts-map.conf

# TLS :8443 for all ACME domains (portal / subdomain / public_proxy) when certs exist
if [[ -x /sync-acme-tls.sh ]]; then
  /sync-acme-tls.sh || echo "WARN: sync-acme-tls failed" >&2
elif [[ -x /sync-public-proxy-tls.sh ]]; then
  /sync-public-proxy-tls.sh || echo "WARN: sync-public-proxy-tls failed" >&2
else
  echo "# no ACME TLS sync script" > /etc/nginx/conf.d/nginx-acme-tls.conf
fi
