#!/usr/bin/env bash
# TLS :443 for every ACME-covered FQDN (portal / subdomain_proxy / public_proxy)
# + HTTP :80 → 301 HTTPS. Terminates TLS then proxies to local :8080.
set -euo pipefail

EXPORTS="${EXPORTS_DIR:-/var/lib/sso-portal/exports}"
CERTS="${CERTS_DIR:-/etc/nginx/ssl}"
OUT="/etc/nginx/conf.d/nginx-acme-tls.conf"
# Ancien nom — ne plus y copier la conf (include conf.d/*.conf → duplicate default_server).
LEGACY_STUB="/etc/nginx/conf.d/nginx-public-proxy-apps-tls.conf"
MANIFEST="${EXPORTS}/acme-domains.json"
LOCAL_SSL="/etc/nginx/ssl-local"
DEFAULT_CERT="${LOCAL_SSL}/_default/fullchain.pem"
DEFAULT_KEY="${LOCAL_SSL}/_default/privkey.pem"

mkdir -p /var/log/nginx/apps "$LOCAL_SSL/_default"

ensure_default_cert() {
  if [[ -f "$DEFAULT_CERT" && -f "$DEFAULT_KEY" ]]; then
    return 0
  fi
  if ! command -v openssl >/dev/null 2>&1; then
    echo "WARN: openssl missing — cannot bootstrap default TLS cert" >&2
    return 1
  fi
  openssl req -x509 -nodes -newkey rsa:2048 -days 30 \
    -keyout "$DEFAULT_KEY" \
    -out "$DEFAULT_CERT" \
    -subj "/CN=bastion-default" 2>/dev/null
}

ensure_default_cert || true

retire_legacy_duplicate() {
  # Stub comment-only so old includes / docs still resolve, without a second server{}.
  cat > "$LEGACY_STUB" <<'EOF'
# Deprecated alias — TLS edge lives in nginx-acme-tls.conf only.
# (Do not duplicate listen default_server here.)
EOF
}

retire_legacy_duplicate

{
  echo "# Generated by sync-acme-tls.sh — do not edit"
  echo "# listen 80 → 301 https://\$host\$request_uri ; listen 443 ssl → :8080"
  echo ""
  echo "# HTTP → HTTPS (edge nginx, no Traefik)"
  echo "server {"
  echo "    listen 0.0.0.0:80 default_server;"
  echo "    server_name _;"
  echo "    return 301 https://\$host\$request_uri;"
  echo "}"
  echo ""
} > "$OUT"

if [[ -f "$DEFAULT_CERT" && -f "$DEFAULT_KEY" ]]; then
  cat >> "$OUT" <<EOF
# Default HTTPS — unknown/missing SNI (curl -k https://IP, reverse01→IP).
# Must proxy to :8080 so Host-based vhosts still work (do NOT hard-503 here).
server {
    listen 0.0.0.0:443 ssl default_server;
    server_name _;

    ssl_certificate     ${DEFAULT_CERT};
    ssl_certificate_key ${DEFAULT_KEY};
    ssl_protocols TLSv1.2 TLSv1.3;

    include /etc/nginx/includes/security-headers.conf;

    absolute_redirect off;
    port_in_redirect off;

    # CrushFTP (and large portal uploads) hit THIS :443 layer first — without an
    # explicit limit nginx defaults to 1m and returns 413 before :8080 (where
    # transfer already has client_max_body_size 2G). Symptom: POST /U/…~1M fails
    # with "client intended to send too large body" while keepalives still 200.
    client_max_body_size 2G;
    proxy_request_buffering off;
    proxy_buffering off;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        # Required: hop-by-hop Upgrade/Connection are dropped unless re-set
        # (Teleport wss://…/connect/ws fails without these).
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        # oauth2-proxy Set-Cookie (id_token+refresh) often exceeds default 4k/8k
        # → nginx 500 "upstream sent too big header" on /oauth2/*/callback.
        proxy_buffer_size 128k;
        proxy_buffers 8 128k;
        proxy_busy_buffers_size 256k;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_set_header Host \$host;
        # Edge → :8080: peer becomes 127.0.0.1; map only trusts X-Portal-Client-IP
        # from infra peers (see nginx-portal-client-ip.map.conf). Escape \$ in this
        # heredoc — set -u treats bare \$vars as unbound (broke sync after #115).
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Portal-Client-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port 443;
    }
}

EOF
fi

if [[ ! -f "$MANIFEST" ]]; then
  echo "# (no acme-domains.json yet)" >> "$OUT"
  exit 0
fi

emit_rows() {
  if command -v jq >/dev/null 2>&1; then
    jq -r '.domains[] | [.fqdn, .slug, (.family // "app")] | @tsv' "$MANIFEST"
  else
    grep -oE '"fqdn"[[:space:]]*:[[:space:]]*"[^"]+"' "$MANIFEST" \
      | sed 's/.*"\([^"]*\)"$/\1/' \
      | while read -r f; do
          printf '%s\t%s\t%s\n' "$f" "${f%%.*}" "app"
        done
  fi
}

while IFS=$'\t' read -r fqdn slug family; do
  [[ -n "${fqdn:-}" ]] || continue
  cert="$CERTS/$fqdn/fullchain.pem"
  key="$CERTS/$fqdn/privkey.pem"
  if [[ ! -f "$cert" || ! -f "$key" ]]; then
    echo "# skip $fqdn — certs not ready" >> "$OUT"
    continue
  fi
  slug="${slug:-app}"
  family="${family:-app}"
  fqdn_esc="${fqdn//\\/\\\\}"
  fqdn_esc="${fqdn_esc//\"/\\\"}"

  cat >> "$OUT" <<EOF
# [${slug}] ${family} TLS terminator — ${fqdn}
server {
    listen 0.0.0.0:443 ssl;
    server_name ${fqdn_esc};

    ssl_certificate     ${cert};
    ssl_certificate_key ${key};
    ssl_protocols TLSv1.2 TLSv1.3;

    include /etc/nginx/includes/security-headers.conf;
EOF
  if [[ "$family" == "portal" ]]; then
    cat >> "$OUT" <<EOF
    include /etc/nginx/includes/security-headers-portal-csp.conf;
EOF
  fi
  cat >> "$OUT" <<EOF

    absolute_redirect off;
    port_in_redirect off;

    access_log /var/log/nginx/apps/${slug}.access.log app;
    error_log  /var/log/nginx/apps/${slug}.error.log warn;

    # See default_server block — same body limit / streaming on every FQDN.
    client_max_body_size 2G;
    proxy_request_buffering off;
    proxy_buffering off;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        # Required: hop-by-hop Upgrade/Connection are dropped unless re-set
        # (Teleport wss://…/connect/ws fails without these).
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        # oauth2-proxy Set-Cookie (id_token+refresh) often exceeds default 4k/8k
        # → nginx 500 "upstream sent too big header" on /oauth2/*/callback.
        proxy_buffer_size 128k;
        proxy_buffers 8 128k;
        proxy_busy_buffers_size 256k;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_set_header Host \$host;
        # Edge → :8080: peer becomes 127.0.0.1; map only trusts X-Portal-Client-IP
        # from infra peers (see nginx-portal-client-ip.map.conf). Escape \$ in this
        # heredoc — set -u treats bare \$vars as unbound (broke sync after #115).
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Portal-Client-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port 443;
    }
}

EOF
done < <(emit_rows)
