#!/usr/bin/env bash
# TLS :8443 for every ACME-covered FQDN (portal / subdomain_proxy / public_proxy).
# Terminates TLS then proxies to local :8080 so existing Host-based auth/routing applies.
set -euo pipefail

EXPORTS="${EXPORTS_DIR:-/var/lib/sso-portal/exports}"
CERTS="${CERTS_DIR:-/etc/nginx/ssl}"
OUT="/etc/nginx/conf.d/nginx-acme-tls.conf"
# Keep legacy filename as include alias for older images / docs
LEGACY_OUT="/etc/nginx/conf.d/nginx-public-proxy-apps-tls.conf"
MANIFEST="${EXPORTS}/acme-domains.json"

mkdir -p /var/log/nginx/apps

{
  echo "# Generated by sync-acme-tls.sh — do not edit"
  echo "# listen 8443 ssl → http://127.0.0.1:8080 (Host preserved)"
  echo ""
} > "$OUT"

if [[ ! -f "$MANIFEST" ]]; then
  echo "# (no acme-domains.json yet)" >> "$OUT"
  cp -a "$OUT" "$LEGACY_OUT"
  exit 0
fi

emit_rows() {
  if command -v jq >/dev/null 2>&1; then
    jq -r '.domains[] | [.fqdn, .slug, (.family // "app")] | @tsv' "$MANIFEST"
  else
    grep -oE '"fqdn"[[:space:]]*:[[:space:]]*"[^"]+"' "$MANIFEST" \
      | sed 's/.*"\([^"]*\)"$/\1/' \
      | while read -r f; do
          printf '%s\t%s\t%s\n' "$f" "${f%%.*}" "app"
        done
  fi
}

while IFS=$'\t' read -r fqdn slug family; do
  [[ -n "${fqdn:-}" ]] || continue
  cert="$CERTS/$fqdn/fullchain.pem"
  key="$CERTS/$fqdn/privkey.pem"
  if [[ ! -f "$cert" || ! -f "$key" ]]; then
    echo "# skip $fqdn — certs not ready" >> "$OUT"
    continue
  fi
  slug="${slug:-app}"
  family="${family:-app}"
  fqdn_esc="${fqdn//\\/\\\\}"
  fqdn_esc="${fqdn_esc//\"/\\\"}"

  cat >> "$OUT" <<EOF
# [${slug}] ${family} TLS terminator — ${fqdn}
server {
    listen 0.0.0.0:8443 ssl;
    server_name ${fqdn_esc};

    ssl_certificate     ${cert};
    ssl_certificate_key ${key};
    ssl_protocols TLSv1.2 TLSv1.3;

    absolute_redirect off;
    port_in_redirect off;

    access_log /var/log/nginx/apps/${slug}.access.log app;
    error_log  /var/log/nginx/apps/${slug}.error.log warn;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
    }
}

EOF
done < <(emit_rows)

cp -a "$OUT" "$LEGACY_OUT"
