"""Multi-realm Keycloak configuration and Nginx export."""

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.audit import log_action
from app.database import get_db
from app.models import RealmConfig
from app.security import require_internal_token
from app.sso_settings import Settings, get_settings

router = APIRouter(prefix="/api/admin/realms", tags=["realms"])


class RealmCreate(BaseModel):
    slug: str
    keycloak_realm: str
    keycloak_base_url: str
    client_id: str
    oauth2_proxy_port: int
    oauth2_proxy_url: str | None = None
    is_default: bool = False
    enabled: bool = True


class RealmOut(BaseModel):
    slug: str
    keycloak_realm: str
    keycloak_base_url: str
    client_id: str
    oauth2_proxy_port: int
    oauth2_proxy_url: str
    is_default: bool
    enabled: bool

    model_config = {"from_attributes": True}


def _exports_path(settings: Settings) -> Path:
    return Path(settings.exports_dir)


def generate_nginx_realms_conf(db: Session) -> str:
    """Generate the Nginx fragment for all active realms."""
    realms = db.query(RealmConfig).filter_by(enabled=True).all()
    lines = ["# Generated by realm_service — do not edit manually", ""]

    for realm in realms:
        lines.append(f"# Realm: {realm.slug} ({realm.keycloak_realm})")
        lines.append(f"location /oauth2/{realm.slug}/ {{")
        lines.append(f"    proxy_pass {realm.oauth2_proxy_url}/oauth2/;")
        lines.append("    proxy_set_header Host $host;")
        lines.append("    proxy_set_header X-Real-IP $remote_addr;")
        lines.append("    proxy_set_header X-Forwarded-Proto $scheme;")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def export_nginx_realms_conf(db: Session, settings: Settings) -> Path:
    """Write the nginx realms conf file and return its path."""
    exports_path = _exports_path(settings)
    exports_path.mkdir(parents=True, exist_ok=True)
    output = exports_path / "nginx-portal-realms.conf"
    output.write_text(generate_nginx_realms_conf(db), encoding="utf-8")
    return output


def _client_ip(request: Request) -> str:
    return request.headers.get("X-Real-IP", request.client.host if request.client else "")


@router.get("", response_model=list[RealmOut])
def list_realms(
    db: Session = Depends(get_db),
    _token: str = Depends(require_internal_token),
):
    return db.query(RealmConfig).all()


@router.post("", response_model=RealmOut, status_code=201)
def create_realm(
    body: RealmCreate,
    request: Request,
    db: Session = Depends(get_db),
    settings: Settings = Depends(get_settings),
    _token: str = Depends(require_internal_token),
):
    existing = db.query(RealmConfig).filter_by(slug=body.slug).first()
    if existing:
        raise HTTPException(status_code=409, detail=f"Realm '{body.slug}' already exists")

    proxy_url = body.oauth2_proxy_url or f"http://127.0.0.1:{body.oauth2_proxy_port}"

    if body.is_default:
        db.query(RealmConfig).filter_by(is_default=True).update({"is_default": False})

    realm = RealmConfig(
        slug=body.slug,
        keycloak_realm=body.keycloak_realm,
        keycloak_base_url=body.keycloak_base_url,
        client_id=body.client_id,
        oauth2_proxy_port=body.oauth2_proxy_port,
        oauth2_proxy_url=proxy_url,
        is_default=body.is_default,
        enabled=body.enabled,
    )
    db.add(realm)
    db.commit()
    db.refresh(realm)

    export_nginx_realms_conf(db, settings)
    log_action(
        db,
        actor="system",
        action="realm.create",
        target=f"realm:{body.slug}",
        ip_address=_client_ip(request),
    )
    return realm


@router.delete("/{slug}", status_code=204)
def delete_realm(
    slug: str,
    request: Request,
    db: Session = Depends(get_db),
    settings: Settings = Depends(get_settings),
    _token: str = Depends(require_internal_token),
):
    realm = db.query(RealmConfig).filter_by(slug=slug).first()
    if not realm:
        raise HTTPException(status_code=404, detail=f"Realm '{slug}' not found")

    db.delete(realm)
    db.commit()

    export_nginx_realms_conf(db, settings)
    log_action(
        db,
        actor="system",
        action="realm.delete",
        target=f"realm:{slug}",
        ip_address=_client_ip(request),
    )


@router.post("/export")
def export_realms(
    request: Request,
    db: Session = Depends(get_db),
    settings: Settings = Depends(get_settings),
    _token: str = Depends(require_internal_token),
):
    path = export_nginx_realms_conf(db, settings)
    log_action(
        db,
        actor="system",
        action="realm.export",
        target=str(path),
        ip_address=_client_ip(request),
    )
    return {"status": "ok", "path": str(path)}
