"""First-boot / incomplete-config setup wizard (DB-backed site identity)."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from sqlalchemy.orm import Session

from app.audit import log_action
from app.auth_flow import get_default_idp_realm
from app.breakglass_store import has_active_breakglass_account
from app.models import PortalSettings, utcnow
from app.portal_settings_service import ensure_portal_settings
from app.sso_settings import Settings

_PLACEHOLDER_DOMAINS = frozenset(
    {
        "",
        "localhost",
        "portal.example.com",
        "example.com",
    }
)
_DOMAIN_RE = re.compile(
    r"^(?=.{1,253}$)(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))+$"
)
_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,62}$")

SITE_ENV_FILENAME = "bastion-site.env"


@dataclass(frozen=True)
class SetupStep:
    id: str
    label: str
    status: str  # done | current | todo | locked | info
    detail: str = ""
    href: str | None = None


@dataclass(frozen=True)
class SetupStatus:
    needs_wizard: bool
    completed: bool
    portal_domain: str
    default_realm_slug: str
    domain_from_db: bool
    slug_from_db: bool
    has_breakglass: bool
    has_default_realm: bool
    realm_tested_ok: bool
    internal_token_ok: bool
    steps: list[SetupStep]


def normalize_portal_domain(raw: str | None) -> str:
    value = (raw or "").strip().lower()
    if value.startswith("https://"):
        value = value[8:]
    elif value.startswith("http://"):
        value = value[7:]
    value = value.split("/")[0].split(":")[0].strip(".")
    return value


def normalize_realm_slug(raw: str | None) -> str:
    return (raw or "").strip().lower()


def get_effective_portal_domain(db: Session, settings: Settings) -> str:
    row = ensure_portal_settings(db, settings)
    db_val = normalize_portal_domain(getattr(row, "portal_domain", None))
    if db_val:
        return db_val
    return normalize_portal_domain(settings.portal_domain)


def get_effective_default_realm_slug(db: Session, settings: Settings) -> str:
    row = ensure_portal_settings(db, settings)
    db_val = normalize_realm_slug(getattr(row, "default_realm_slug", None))
    if db_val:
        return db_val
    return normalize_realm_slug(settings.sso_portal_default_realm_slug) or "default"


def write_site_env_export(
    settings: Settings,
    *,
    portal_domain: str,
    default_realm_slug: str,
) -> Path:
    """Write exports/bastion-site.env for nginx sync/entrypoint (DB → edge)."""
    exports = Path(settings.exports_dir)
    exports.mkdir(parents=True, exist_ok=True)
    path = exports / SITE_ENV_FILENAME
    domain = normalize_portal_domain(portal_domain)
    slug = normalize_realm_slug(default_realm_slug) or "default"
    body = (
        "# Generated by Bastion setup wizard — do not edit\n"
        f"PORTAL_DOMAIN={domain}\n"
        f"SSO_PORTAL_DEFAULT_REALM_SLUG={slug}\n"
    )
    path.write_text(body, encoding="utf-8")
    return path


def update_site_identity(
    db: Session,
    settings: Settings,
    *,
    portal_domain: str,
    default_realm_slug: str,
    actor: str,
    ip_address: str | None = None,
) -> PortalSettings:
    domain = normalize_portal_domain(portal_domain)
    slug = normalize_realm_slug(default_realm_slug)
    if not domain or domain in _PLACEHOLDER_DOMAINS or not _DOMAIN_RE.match(domain):
        raise ValueError(
            "Indiquez un FQDN portail valide (ex. portal.votredomaine.tld)."
        )
    if not slug or not _SLUG_RE.match(slug):
        raise ValueError(
            "Slug realm invalide (minuscules, chiffres, _ ou -, ex. default)."
        )

    row = ensure_portal_settings(db, settings)
    previous_domain = getattr(row, "portal_domain", None)
    previous_slug = getattr(row, "default_realm_slug", None)
    row.portal_domain = domain
    row.default_realm_slug = slug
    row.updated_at = utcnow()
    row.updated_by = actor
    db.commit()
    db.refresh(row)

    write_site_env_export(settings, portal_domain=domain, default_realm_slug=slug)

    log_action(
        db,
        actor=actor,
        action="portal_settings.site_identity_updated",
        target="portal_settings",
        details={
            "portal_domain": domain,
            "default_realm_slug": slug,
            "previous_domain": previous_domain,
            "previous_slug": previous_slug,
        },
        ip_address=ip_address,
    )
    return row


def mark_setup_wizard_complete(
    db: Session,
    settings: Settings,
    *,
    actor: str,
    ip_address: str | None = None,
) -> PortalSettings:
    status = get_setup_status(db, settings)
    if not status.has_breakglass:
        raise ValueError("Créez d'abord le compte administrateur local.")
    if status.portal_domain in _PLACEHOLDER_DOMAINS:
        raise ValueError("Définissez le FQDN portail avant de terminer.")
    if not status.has_default_realm:
        raise ValueError("Configurez et activez un realm OIDC par défaut.")

    row = ensure_portal_settings(db, settings)
    row.setup_wizard_completed_at = utcnow()
    row.updated_at = utcnow()
    row.updated_by = actor
    db.commit()
    db.refresh(row)
    log_action(
        db,
        actor=actor,
        action="portal_settings.setup_wizard_completed",
        target="portal_settings",
        details={"portal_domain": status.portal_domain},
        ip_address=ip_address,
    )
    return row


def get_setup_status(db: Session, settings: Settings) -> SetupStatus:
    row = ensure_portal_settings(db, settings)
    completed = getattr(row, "setup_wizard_completed_at", None) is not None
    db_domain = normalize_portal_domain(getattr(row, "portal_domain", None))
    db_slug = normalize_realm_slug(getattr(row, "default_realm_slug", None))
    portal_domain = db_domain or normalize_portal_domain(settings.portal_domain)
    default_slug = (
        db_slug
        or normalize_realm_slug(settings.sso_portal_default_realm_slug)
        or "default"
    )

    has_bg = has_active_breakglass_account(db)
    realm = get_default_idp_realm(db)
    has_realm = realm is not None
    realm_tested = bool(
        has_realm and (getattr(realm, "last_test_status", None) or "").lower() == "ok"
    )
    token_ok = bool((settings.vault_portal_internal_token or "").strip())

    domain_ok = portal_domain not in _PLACEHOLDER_DOMAINS and bool(
        _DOMAIN_RE.match(portal_domain)
    )

    # Mature installs (real domain via .env + default realm) are not nagged.
    if completed:
        needs = False
    elif domain_ok and has_realm and has_bg:
        needs = False
    else:
        needs = has_bg and (not domain_ok or not has_realm)

    steps: list[SetupStep] = [
        SetupStep(
            id="admin",
            label="Compte admin local",
            status="done" if has_bg else "todo",
            detail="Break-glass créé" if has_bg else "Requis via /auth/setup (LAN)",
            href=None if has_bg else "/auth/setup",
        ),
        SetupStep(
            id="site",
            label="Identité du portail",
            status="done" if domain_ok else ("current" if has_bg else "locked"),
            detail=portal_domain if domain_ok else "FQDN + slug realm (stockés en base)",
            href="/admin/setup-wizard#site" if has_bg else None,
        ),
        SetupStep(
            id="oidc",
            label="Realm OIDC",
            status=(
                "done"
                if has_realm
                else ("current" if domain_ok else ("todo" if has_bg else "locked"))
            ),
            detail=(
                f"Realm « {realm.slug} »"
                + (" (test OK)" if realm_tested else " — tester puis Apply")
                if has_realm
                else "Issuer, client, secrets → Realms"
            ),
            href="/admin/realms/new" if has_bg else None,
        ),
        SetupStep(
            id="docker",
            label="Secrets Docker (.env)",
            status="done" if token_ok else "info",
            detail=(
                "VAULT_PORTAL_INTERNAL_TOKEN présent"
                if token_ok
                else "Token interne + clés DB restent dans .env (nginx au démarrage)"
            ),
            href=None,
        ),
    ]

    return SetupStatus(
        needs_wizard=needs,
        completed=completed or (domain_ok and has_realm and has_bg),
        portal_domain=portal_domain,
        default_realm_slug=default_slug,
        domain_from_db=bool(db_domain),
        slug_from_db=bool(db_slug),
        has_breakglass=has_bg,
        has_default_realm=has_realm,
        realm_tested_ok=realm_tested,
        internal_token_ok=token_ok,
        steps=steps,
    )


def setup_status_dict(status: SetupStatus) -> dict[str, Any]:
    return {
        "needs_wizard": status.needs_wizard,
        "completed": status.completed,
        "portal_domain": status.portal_domain,
        "default_realm_slug": status.default_realm_slug,
        "domain_from_db": status.domain_from_db,
        "slug_from_db": status.slug_from_db,
        "has_breakglass": status.has_breakglass,
        "has_default_realm": status.has_default_realm,
        "realm_tested_ok": status.realm_tested_ok,
        "internal_token_ok": status.internal_token_ok,
        "steps": [
            {
                "id": s.id,
                "label": s.label,
                "status": s.status,
                "detail": s.detail,
                "href": s.href,
            }
            for s in status.steps
        ],
    }
