---
- name: Validate nginx configuration
  ansible.builtin.command: nginx -t
  listen: Reload nginx
  changed_when: false

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: Reload nginx

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart sso-portal
  ansible.builtin.systemd:
    name: sso-portal
    state: restarted
    daemon_reload: true
