"""Export nginx map of known Hosts for unknown-Host discovery.

Hosts listed with value ``0`` are known (portal / apps / infra). Everything else
is unknown (``default 1`` in the map wrapper) and is redirected to the discovery
stub on the portal default_server — without a second default_server.
"""

from __future__ import annotations

import re
from pathlib import Path

from sqlalchemy.orm import Session

from app.access_modes import normalize_access_mode
from app.models import App
from app.sso_settings import Settings

_SERVER_NAME_RE = re.compile(
    r"^\s*server_name\s+([^;]+);",
    re.IGNORECASE | re.MULTILINE,
)
_SAFE_HOST = re.compile(r"^[a-z0-9]([a-z0-9.-]{0,251}[a-z0-9])?$")


def normalize_hostname(raw: str | None) -> str | None:
    """Lowercase Host without port; None if empty/invalid for discovery."""
    host = (raw or "").strip().lower().split("%")[0]
    if not host or host == "*":
        return None
    # Strip :port — reject IPv6 (colons break nginx map keys).
    if ":" in host:
        if host.startswith("["):
            return None
        host = host.rsplit(":", 1)[0]
    host = host.strip(".")
    if not host:
        return None
    if host in ("127.0.0.1", "localhost"):
        return host
    if not _SAFE_HOST.match(host):
        return None
    return host


def _infra_fqdns_from_export(settings: Settings) -> set[str]:
    path = Path(settings.exports_dir) / "nginx-infra-proxy-apps.conf"
    if not path.is_file():
        return set()
    text = path.read_text(encoding="utf-8")
    out: set[str] = set()
    for match in _SERVER_NAME_RE.finditer(text):
        for token in match.group(1).split():
            host = normalize_hostname(token)
            if host and host not in ("_", "*"):
                out.add(host)
    return out


def collect_known_hostnames(db: Session, settings: Settings) -> list[str]:
    """Portal + loopback + enabled app FQDNs + infra proxy server_names."""
    # Never include IPv6 (::1) — colons are invalid as nginx map keys.
    known: set[str] = {"127.0.0.1", "localhost"}
    portal = normalize_hostname(settings.portal_domain)
    if portal:
        known.add(portal)
    for app in db.query(App).filter_by(enabled=True).order_by(App.slug).all():
        mode = normalize_access_mode(app.access_mode)
        if mode not in ("subdomain_proxy", "public_proxy"):
            continue
        fqdn = normalize_hostname(app.public_fqdn)
        if fqdn:
            known.add(fqdn)
    known.update(_infra_fqdns_from_export(settings))
    return sorted(known)


def generate_known_hosts_map(db: Session, settings: Settings) -> str:
    lines = [
        "# Generated by bastion-app — known Hosts map body (hostname 0;)",
        "# Consumed by nginx entrypoint (inlined into the unknown-host map).",
        "",
    ]
    for host in collect_known_hostnames(db, settings):
        lines.append(f"{host} 0;")
    lines.append("")
    return "\n".join(lines)


def write_known_hosts_map(db: Session, settings: Settings) -> Path:
    exports = Path(settings.exports_dir)
    exports.mkdir(parents=True, exist_ok=True)
    path = exports / "nginx-known-hosts.map"
    path.write_text(generate_known_hosts_map(db, settings), encoding="utf-8")
    return path
