"""IHM-driven ModSecurity reactivation with smoke probes and auto-rollback.

Portal family only (runbook §2). Success = nginx -t + HTTP smoke (not nginx -t alone):
the 2026-08-06 failure mode was request-time HTTP 500 while /api/health stayed 200.
"""

from __future__ import annotations

import json
import logging
import subprocess
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from sqlalchemy.orm import Session

from app.bastion.nginx_waf_export import (
    MODE_DETECTION,
    MODE_OFF,
    MODE_ON,
    ensure_active_profile,
    read_effective_status,
    record_waf_apply_metadata,
    restore_waf_exports_previous,
    waf_exports_dir,
    write_waf_exports,
)
from app.models import WafProfile
from app.sso_settings import Settings

logger = logging.getLogger(__name__)

ARM_FILENAME = "waf-engine-arm.json"
PORTAL_SWITCH_FILENAME = "modsecurity-portal-switch.conf"
SMOKE_TIMEOUT_SEC = 8
RELOAD_WAIT_SEC = 6
SMOKE_RETRIES = 3


def arm_state_path(settings: Settings) -> Path:
    return waf_exports_dir(settings) / ARM_FILENAME


def portal_switch_export_path(settings: Settings) -> Path:
    return Path(settings.exports_dir) / PORTAL_SWITCH_FILENAME


def read_arm_state(settings: Settings) -> dict[str, Any]:
    path = arm_state_path(settings)
    if not path.is_file():
        return {"armed": False, "present": False}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"armed": False, "present": False, "error": "unreadable"}
    if not isinstance(data, dict):
        return {"armed": False, "present": False, "error": "invalid"}
    data["present"] = True
    data["armed"] = bool(data.get("armed"))
    return data


def render_portal_switch(*, enabled: bool) -> str:
    state = "on" if enabled else "off"
    return (
        "# Generated by waf_reactivation — do not edit\n"
        f"# Portal server-level ModSecurity connector ({state}).\n"
        f"modsecurity {state};\n"
    )


def render_engine_mode_line(mode: str) -> str:
    mapping = {
        MODE_OFF: "SecRuleEngine Off",
        MODE_DETECTION: "SecRuleEngine DetectionOnly",
        MODE_ON: "SecRuleEngine On",
    }
    line = mapping.get(mode, "SecRuleEngine Off")
    return (
        "# Generated by waf_reactivation — do not edit\n"
        f"{line}\n"
    )


def write_arm_state(settings: Settings, payload: dict[str, Any]) -> Path:
    path = arm_state_path(settings)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = dict(payload)
    body["updated_at"] = datetime.now(timezone.utc).isoformat()
    path.write_text(json.dumps(body, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def _compose_bases(settings: Settings) -> list[Path]:
    bases: list[Path] = []
    compose_dir = getattr(settings, "compose_dir", None)
    if compose_dir:
        bases.append(Path(compose_dir))
    bases.append(Path.cwd())
    return bases


def docker_nginx_sh(settings: Settings, script: str, *, timeout: int = 90) -> tuple[bool, str, bool]:
    """Run a shell script inside the nginx compose service.

    Returns (ok, detail, skipped).
    ``skipped=True`` when docker/compose is unavailable (normal in bastion-app prod).
    """
    for base in _compose_bases(settings):
        compose = base / "docker-compose.yml"
        if not compose.is_file():
            continue
        try:
            proc = subprocess.run(
                [
                    "docker",
                    "compose",
                    "exec",
                    "-T",
                    "nginx",
                    "sh",
                    "-c",
                    script,
                ],
                cwd=str(base),
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            return (
                True,
                f"docker compose exec nginx non exécuté ({exc}) — watcher nginx validera",
                True,
            )
        out = ((proc.stdout or "") + (proc.stderr or "")).strip()
        if proc.returncode != 0:
            lower = out.lower()
            # Docker daemon / binary missing → same as Appliquer: watcher path.
            docker_unavailable = any(
                token in lower
                for token in (
                    "cannot connect",
                    "error during connect",
                    "docker daemon",
                    "permission denied while trying to connect",
                    "executable file not found",
                    "docker: command not found",
                    "no such file or directory",
                    "the system cannot find",
                )
            ) or proc.returncode in (127, 125, 126)
            if docker_unavailable:
                return (
                    True,
                    "docker compose exec indisponible — watcher bastion-nginx validera",
                    True,
                )
            return False, out or f"exit {proc.returncode}", False
        return True, out or "ok", False
    return (
        True,
        "sync/reload délégué au watcher bastion-nginx (pas de docker-compose.yml / docker.sock)",
        True,
    )


def sync_and_reload(settings: Settings) -> tuple[bool, str]:
    """Trigger nginx sync+reload when possible; otherwise rely on watch-exports-reload.

    Production bastion-app has no docker.sock — writing exports is enough; the nginx
    container polls the shared volume and runs sync + nginx -t + reload.
    """
    ok, detail, skipped = docker_nginx_sh(
        settings,
        "/sync-exports-to-confd.sh && nginx -t && nginx -s reload && /export-waf-snapshot.sh",
        timeout=120,
    )
    if skipped:
        # Nudge mtime so watcher always sees a change even if content identical.
        try:
            arm = arm_state_path(settings)
            if arm.is_file():
                arm.touch()
        except OSError:
            pass
    return ok, detail


def wait_for_nginx_edge(*, attempts: int = 12, delay_sec: float = 1.5) -> dict[str, Any]:
    """Poll nginx until edge responds (watcher reload lag)."""
    last: dict[str, Any] = {"ok": False}
    for i in range(attempts):
        last = _http_probe(
            "http://nginx:8080/_portal_nginx_ok",
            expect_status=200,
            expect_not_5xx=True,
        )
        if last.get("ok"):
            last["attempts"] = i + 1
            return last
        time.sleep(delay_sec)
    last["attempts"] = attempts
    return last


def _http_probe(
    url: str,
    *,
    host: str | None = None,
    expect_not_5xx: bool = True,
    expect_status: int | None = None,
) -> dict[str, Any]:
    headers = {}
    if host:
        headers["Host"] = host
    req = urllib.request.Request(url, headers=headers, method="GET")
    try:
        with urllib.request.urlopen(req, timeout=SMOKE_TIMEOUT_SEC) as resp:
            code = int(resp.status)
            body_len = len(resp.read(4096) or b"")
    except urllib.error.HTTPError as exc:
        code = int(exc.code)
        body_len = 0
    except Exception as exc:  # noqa: BLE001 — probe must never raise
        return {
            "url": url,
            "ok": False,
            "error": str(exc),
            "status": None,
        }

    ok = True
    reason = "ok"
    if expect_status is not None and code != expect_status:
        ok = False
        reason = f"expected {expect_status}, got {code}"
    elif expect_not_5xx and code >= 500:
        ok = False
        reason = f"HTTP {code} (échec type incident 2026-08-06)"
    return {
        "url": url,
        "host": host,
        "status": code,
        "bytes": body_len,
        "ok": ok,
        "reason": reason,
    }


def smoke_portal_probes(settings: Settings) -> dict[str, Any]:
    """Reliable post-reload checks. Fail closed if probes cannot run."""
    domain = (settings.portal_domain or "portal.localhost").strip()
    probes: list[dict[str, Any]] = []

    # Local nginx health (modsecurity off on this location) — connectivity.
    for attempt in range(SMOKE_RETRIES):
        p = _http_probe(
            "http://nginx:8080/_portal_nginx_ok",
            expect_status=200,
            expect_not_5xx=True,
        )
        probes.append(p)
        if p.get("ok"):
            break
        time.sleep(1 + attempt)

    # App health via portal edge (location also modsecurity off).
    probes.append(
        _http_probe(
            "http://nginx:8080/api/health",
            host=domain,
            expect_not_5xx=True,
        )
    )

    # Request-time ModSec path — this is what broke on 2026-08-06.
    login = _http_probe(
        f"https://{domain}/auth/login",
        expect_not_5xx=True,
    )
    if not login.get("ok") and login.get("error"):
        # Fallback: HTTP via nginx alias (TLS may fail in lab).
        login = _http_probe(
            "http://nginx:80/auth/login",
            host=domain,
            expect_not_5xx=True,
        )
    probes.append(login)

    # Soft home probe (redirects OK, 5xx not OK).
    home = _http_probe(
        "http://nginx:80/",
        host=domain,
        expect_not_5xx=True,
    )
    probes.append(home)

    ok = all(bool(p.get("ok")) for p in probes)
    return {
        "ok": ok,
        "probes": probes,
        "failed": [p for p in probes if not p.get("ok")],
    }


def _force_disarmed_files(settings: Settings) -> None:
    """Write Off switch + Off engine + armed=false (rollback target)."""
    exports = Path(settings.exports_dir)
    exports.mkdir(parents=True, exist_ok=True)
    mod = waf_exports_dir(settings)
    mod.mkdir(parents=True, exist_ok=True)

    switch = portal_switch_export_path(settings)
    switch.write_text(render_portal_switch(enabled=False), encoding="utf-8")
    (mod / "engine-mode-generated.conf").write_text(
        render_engine_mode_line(MODE_OFF), encoding="utf-8"
    )
    write_arm_state(
        settings,
        {
            "armed": False,
            "family": "portal",
            "target_mode": MODE_OFF,
            "reason": "disarmed",
        },
    )


def disarm_engine(
    settings: Settings,
    *,
    actor: str,
    reason: str = "manual_disarm",
) -> dict[str, Any]:
    """Cut ModSecurity connector + SecRuleEngine Off and reload."""
    _force_disarmed_files(settings)
    write_arm_state(
        settings,
        {
            "armed": False,
            "family": "portal",
            "target_mode": MODE_OFF,
            "reason": reason,
            "actor": actor,
        },
    )
    ok, detail = sync_and_reload(settings)
    if ok and "watcher" in detail.lower():
        wait_for_nginx_edge()
    smoke = smoke_portal_probes(settings) if ok else {"ok": False, "probes": [], "failed": []}
    return {
        "ok": bool(ok and smoke.get("ok")),
        "disarmed": True,
        "sync_detail": detail,
        "smoke": smoke,
    }


def reactivate_engine(
    db: Session,
    settings: Settings,
    *,
    actor: str,
    confirm: bool,
    target_mode: str = MODE_DETECTION,
    validate: Callable[[Settings], tuple[bool, str]] | None = None,
    smoke: Callable[[Settings], dict[str, Any]] | None = None,
    sync_reload: Callable[[Settings], tuple[bool, str]] | None = None,
) -> dict[str, Any]:
    """Arm portal ModSecurity (DetectionOnly by default), smoke, rollback on failure."""
    if not confirm:
        return {
            "ok": False,
            "error": "Confirmation requise pour réactiver ModSecurity.",
            "rolled_back": False,
        }

    mode = target_mode if target_mode in {MODE_DETECTION, MODE_ON} else MODE_DETECTION
    # First IHM reactivation always prefers DetectionOnly even if profile says On.
    if mode == MODE_ON:
        mode = MODE_DETECTION

    profile = ensure_active_profile(db)
    previous_mode = profile.mode

    # Snapshot previous arm / files for rollback beyond *.prev
    prev_arm = read_arm_state(settings)

    # Stage: update profile to DetectionOnly so exports match intent
    profile.mode = MODE_DETECTION
    db.commit()

    write_arm_state(
        settings,
        {
            "armed": True,
            "family": "portal",
            "target_mode": MODE_DETECTION,
            "actor": actor,
            "previous_mode": previous_mode,
            "phase": "arming",
        },
    )

    # Write full WAF exports (engine DetectionOnly from profile)
    paths = write_waf_exports(db, settings)
    portal_switch_export_path(settings).write_text(
        render_portal_switch(enabled=True), encoding="utf-8"
    )
    paths[PORTAL_SWITCH_FILENAME] = str(portal_switch_export_path(settings))
    paths[ARM_FILENAME] = str(arm_state_path(settings))

    sync_fn = sync_reload or sync_and_reload
    smoke_fn = smoke or smoke_portal_probes

    sync_ok, sync_detail = sync_fn(settings)
    if not sync_ok:
        _rollback(
            db,
            settings,
            profile=profile,
            previous_mode=previous_mode,
            prev_arm=prev_arm,
            actor=actor,
            reason=f"sync/nginx -t failed: {sync_detail}",
            sync_reload=sync_fn,
        )
        return {
            "ok": False,
            "error": f"Sync/reload échoué — rollback. {sync_detail}",
            "rolled_back": True,
            "paths": paths,
            "sync_detail": sync_detail,
        }

    # Wait for watcher reload when docker exec was skipped (prod).
    if smoke is None and sync_reload is None:
        edge = wait_for_nginx_edge()
        if not edge.get("ok"):
            time.sleep(RELOAD_WAIT_SEC)

    smoke_result = smoke_fn(settings)
    if not smoke_result.get("ok"):
        _rollback(
            db,
            settings,
            profile=profile,
            previous_mode=previous_mode,
            prev_arm=prev_arm,
            actor=actor,
            reason="smoke_failed",
            sync_reload=sync_fn,
        )
        failed = smoke_result.get("failed") or []
        return {
            "ok": False,
            "error": (
                "Smoke post-reload en échec (HTTP 5xx ou sonde injoignable) — "
                "rollback automatique vers Off."
            ),
            "rolled_back": True,
            "paths": paths,
            "smoke": smoke_result,
            "failed_probes": failed,
            "sync_detail": sync_detail,
        }

    write_arm_state(
        settings,
        {
            "armed": True,
            "family": "portal",
            "target_mode": MODE_DETECTION,
            "actor": actor,
            "previous_mode": previous_mode,
            "phase": "active",
            "last_smoke_ok": True,
            "last_smoke_at": datetime.now(timezone.utc).isoformat(),
            "smoke": smoke_result,
        },
    )
    record_waf_apply_metadata(
        settings,
        actor=actor,
        nginx_t_ok=True,
        nginx_t_detail=f"reactivate ok; {sync_detail}",
        nginx_t_skipped=False,
    )
    return {
        "ok": True,
        "rolled_back": False,
        "paths": paths,
        "mode": MODE_DETECTION,
        "family": "portal",
        "smoke": smoke_result,
        "sync_detail": sync_detail,
        "effective": read_effective_status(settings),
        "message": (
            "Moteur portal réactivé en DetectionOnly. Smoke OK. "
            "Passer en On seulement après période d'observation."
        ),
    }


def _rollback(
    db: Session,
    settings: Settings,
    *,
    profile: WafProfile,
    previous_mode: str,
    prev_arm: dict[str, Any],
    actor: str,
    reason: str,
    sync_reload: Callable[[Settings], tuple[bool, str]] | None = None,
) -> None:
    logger.warning("waf reactivation rollback: %s", reason)
    restore_waf_exports_previous(settings)
    _force_disarmed_files(settings)
    profile.mode = MODE_OFF
    db.commit()
    write_arm_state(
        settings,
        {
            "armed": False,
            "family": "portal",
            "target_mode": MODE_OFF,
            "actor": actor,
            "reason": reason,
            "rolled_back": True,
            "previous_arm": {
                k: prev_arm.get(k) for k in ("armed", "target_mode", "phase") if k in prev_arm
            },
        },
    )
    sync_fn = sync_reload or sync_and_reload
    try:
        sync_fn(settings)
    except Exception:  # noqa: BLE001
        logger.exception("sync after rollback failed")
    if sync_reload is None:
        try:
            smoke_portal_probes(settings)
        except Exception:  # noqa: BLE001
            logger.exception("smoke after rollback failed")
