"""Réactivation ModSecurity depuis l'admin : DetectionOnly, sondes HTTP, rollback.

Portail d'abord, sous-domaines ensuite. Promotion subdomain DetectionOnly → On
avec smoke + rollback vers DetectionOnly. nginx -t seul ne suffit pas : les
sondes HTTP doivent passer (un 500 à la requête peut coexister avec
/api/health = 200).
"""

from __future__ import annotations

import json
import logging
import subprocess
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from sqlalchemy.orm import Session

from app.bastion.nginx_waf_export import (
    MODE_DETECTION,
    MODE_OFF,
    MODE_ON,
    ensure_active_profile,
    read_effective_status,
    record_waf_apply_metadata,
    restore_waf_exports_previous,
    waf_exports_dir,
    write_waf_exports,
)
from app.models import App, WafProfile
from app.sso_settings import Settings

logger = logging.getLogger(__name__)

ARM_FILENAME = "waf-engine-arm.json"
PORTAL_SWITCH_FILENAME = "modsecurity-portal-switch.conf"
SUBDOMAIN_SWITCH_FILENAME = "modsecurity-subdomain-switch.conf"
PUBLIC_SWITCH_FILENAME = "modsecurity-public-switch.conf"
ENGINE_SUBDOMAIN_MODE_FILENAME = "engine-subdomain-mode-generated.conf"
SUBDOMAIN_SMOKE_HOST_LIMIT = 5
SMOKE_TIMEOUT_SEC = 8
RELOAD_WAIT_SEC = 6
SMOKE_RETRIES = 3


class _NoRedirectHandler(urllib.request.HTTPRedirectHandler):
    """Probes must not follow 302 (subdomain /auth/login nesting)."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):  # noqa: ANN001
        return None


_PROBE_OPENER = urllib.request.build_opener(_NoRedirectHandler())


def arm_state_path(settings: Settings) -> Path:
    return waf_exports_dir(settings) / ARM_FILENAME


def portal_switch_export_path(settings: Settings) -> Path:
    return Path(settings.exports_dir) / PORTAL_SWITCH_FILENAME


def subdomain_switch_export_path(settings: Settings) -> Path:
    return Path(settings.exports_dir) / SUBDOMAIN_SWITCH_FILENAME


def public_switch_export_path(settings: Settings) -> Path:
    return Path(settings.exports_dir) / PUBLIC_SWITCH_FILENAME


def subdomain_engine_mode_path(settings: Settings) -> Path:
    return waf_exports_dir(settings) / ENGINE_SUBDOMAIN_MODE_FILENAME


def read_subdomain_armed(settings: Settings) -> bool:
    arm = read_arm_state(settings)
    sub = arm.get("subdomain")
    if isinstance(sub, dict) and "armed" in sub:
        return bool(sub.get("armed"))
    return bool(arm.get("subdomain_armed"))


def list_subdomain_smoke_hosts(db: Session) -> list[str]:
    rows = (
        db.query(App.public_fqdn)
        .filter(
            App.enabled.is_(True),
            App.access_mode == "subdomain_proxy",
            App.public_fqdn.isnot(None),
        )
        .order_by(App.slug)
        .all()
    )
    hosts: list[str] = []
    for (fqdn,) in rows:
        host = str(fqdn or "").strip().lower()
        if host and host not in hosts:
            hosts.append(host)
    return hosts


def read_arm_state(settings: Settings) -> dict[str, Any]:
    path = arm_state_path(settings)
    if not path.is_file():
        return {"armed": False, "present": False}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"armed": False, "present": False, "error": "unreadable"}
    if not isinstance(data, dict):
        return {"armed": False, "present": False, "error": "invalid"}
    data["present"] = True
    data["armed"] = bool(data.get("armed"))
    return data


def render_portal_switch(*, enabled: bool) -> str:
    return render_modsecurity_switch(family="portal", enabled=enabled)


def render_modsecurity_switch(*, family: str, enabled: bool) -> str:
    state = "on" if enabled else "off"
    label = {
        "portal": "Portal",
        "subdomain": "Subdomain",
        "public": "Public proxy",
    }.get(family, family)
    return (
        "# Generated by waf_reactivation — do not edit\n"
        f"# {label} server-level ModSecurity connector ({state}).\n"
        f"modsecurity {state};\n"
    )


def render_subdomain_switch(*, enabled: bool) -> str:
    return render_modsecurity_switch(family="subdomain", enabled=enabled)


def render_public_switch(*, enabled: bool) -> str:
    return render_modsecurity_switch(family="public", enabled=enabled)


def render_engine_mode_line(mode: str) -> str:
    mapping = {
        MODE_OFF: "SecRuleEngine Off",
        MODE_DETECTION: "SecRuleEngine DetectionOnly",
        MODE_ON: "SecRuleEngine On",
    }
    line = mapping.get(mode, "SecRuleEngine Off")
    return (
        "# Generated by waf_reactivation — do not edit\n"
        f"{line}\n"
    )


def write_arm_state(settings: Settings, payload: dict[str, Any]) -> Path:
    path = arm_state_path(settings)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = dict(payload)
    body["updated_at"] = datetime.now(timezone.utc).isoformat()
    path.write_text(json.dumps(body, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def _compose_bases(settings: Settings) -> list[Path]:
    bases: list[Path] = []
    compose_dir = getattr(settings, "compose_dir", None)
    if compose_dir:
        bases.append(Path(compose_dir))
    bases.append(Path.cwd())
    return bases


def docker_nginx_sh(settings: Settings, script: str, *, timeout: int = 90) -> tuple[bool, str, bool]:
    """Run a shell script inside the nginx compose service.

    Returns (ok, detail, skipped).
    ``skipped=True`` when docker/compose is unavailable (normal in bastion-app prod).
    """
    for base in _compose_bases(settings):
        compose = base / "docker-compose.yml"
        if not compose.is_file():
            continue
        try:
            proc = subprocess.run(
                [
                    "docker",
                    "compose",
                    "exec",
                    "-T",
                    "nginx",
                    "sh",
                    "-c",
                    script,
                ],
                cwd=str(base),
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            return (
                True,
                f"docker compose exec nginx non exécuté ({exc}) — watcher nginx validera",
                True,
            )
        out = ((proc.stdout or "") + (proc.stderr or "")).strip()
        if proc.returncode != 0:
            lower = out.lower()
            # Docker daemon / binary missing → same as Appliquer: watcher path.
            docker_unavailable = any(
                token in lower
                for token in (
                    "cannot connect",
                    "error during connect",
                    "docker daemon",
                    "permission denied while trying to connect",
                    "executable file not found",
                    "docker: command not found",
                    "no such file or directory",
                    "the system cannot find",
                )
            ) or proc.returncode in (127, 125, 126)
            if docker_unavailable:
                return (
                    True,
                    "docker compose exec indisponible — watcher bastion-nginx validera",
                    True,
                )
            return False, out or f"exit {proc.returncode}", False
        return True, out or "ok", False
    return (
        True,
        "sync/reload délégué au watcher bastion-nginx (pas de docker-compose.yml / docker.sock)",
        True,
    )


def sync_and_reload(settings: Settings) -> tuple[bool, str]:
    """Trigger nginx sync+reload when possible; otherwise rely on watch-exports-reload.

    Production bastion-app has no docker.sock — writing exports is enough; the nginx
    container polls the shared volume and runs sync + nginx -t + reload.
    """
    ok, detail, skipped = docker_nginx_sh(
        settings,
        "/sync-exports-to-confd.sh && nginx -t && nginx -s reload && /export-waf-snapshot.sh",
        timeout=120,
    )
    if skipped:
        # Nudge mtime so watcher always sees a change even if content identical.
        try:
            arm = arm_state_path(settings)
            if arm.is_file():
                arm.touch()
        except OSError:
            pass
    return ok, detail


def wait_for_nginx_edge(
    settings: Settings | None = None,
    *,
    attempts: int = 12,
    delay_sec: float = 1.5,
) -> dict[str, Any]:
    """Poll nginx until edge responds (watcher reload lag).

    Must send a known Host (portal domain or 127.0.0.1). Without it, urllib
    uses Host ``nginx`` → ``$bastion_unknown_host`` → neutral 403.
    """
    host = _smoke_host(settings)
    last: dict[str, Any] = {"ok": False}
    for i in range(attempts):
        last = _http_probe(
            "http://nginx:8080/_portal_nginx_ok",
            host=host,
            expect_status=200,
            expect_not_5xx=True,
        )
        if last.get("ok"):
            last["attempts"] = i + 1
            return last
        time.sleep(delay_sec)
    last["attempts"] = attempts
    return last


def _smoke_host(settings: Settings | None) -> str:
    if settings is not None:
        domain = (settings.portal_domain or "").strip()
        if domain:
            return domain
    return "127.0.0.1"


def _http_probe(
    url: str,
    *,
    host: str | None = None,
    expect_not_5xx: bool = True,
    expect_status: int | None = None,
) -> dict[str, Any]:
    headers = {}
    if host:
        headers["Host"] = host
    req = urllib.request.Request(url, headers=headers, method="GET")
    try:
        with _PROBE_OPENER.open(req, timeout=SMOKE_TIMEOUT_SEC) as resp:
            code = int(resp.status)
            body_len = len(resp.read(4096) or b"")
    except urllib.error.HTTPError as exc:
        code = int(exc.code)
        body_len = 0
    except Exception as exc:  # noqa: BLE001 — probe must never raise
        return {
            "url": url,
            "ok": False,
            "error": str(exc),
            "status": None,
        }

    ok = True
    reason = "ok"
    if expect_status is not None and code != expect_status:
        ok = False
        reason = f"expected {expect_status}, got {code}"
    elif expect_not_5xx and code >= 500:
        ok = False
        reason = f"HTTP {code}"
    return {
        "url": url,
        "host": host,
        "status": code,
        "bytes": body_len,
        "ok": ok,
        "reason": reason,
    }


def smoke_portal_probes(settings: Settings) -> dict[str, Any]:
    """Reliable post-reload checks via the internal nginx edge (not public HTTPS).

    Fail closed on ModSec-protected paths. External HTTPS is informational only —
    hairpin/DNS from bastion-app often fails and must not alone trigger rollback.

    All :8080 probes use the portal Host header. Host ``nginx`` is unknown and
    yields HTTP 403 via ``/__bastion_unknown_host`` (false smoke failure).
    """
    domain = _smoke_host(settings)
    base = "http://nginx:8080"
    probes: list[dict[str, Any]] = []

    # Connectivity (modsecurity off on this location).
    for attempt in range(SMOKE_RETRIES):
        p = _http_probe(
            f"{base}/_portal_nginx_ok",
            host=domain,
            expect_status=200,
            expect_not_5xx=True,
        )
        p["critical"] = True
        probes.append(p)
        if p.get("ok"):
            break
        time.sleep(1 + attempt)

    # App health via portal edge (location modsecurity off).
    health = _http_probe(
        f"{base}/api/health",
        host=domain,
        expect_not_5xx=True,
    )
    health["critical"] = True
    probes.append(health)

    # Chemin inspecté par ModSecurity (login) — edge interne uniquement.
    login = _http_probe(
        f"{base}/auth/login",
        host=domain,
        expect_not_5xx=True,
    )
    login["critical"] = True
    probes.append(login)

    home = _http_probe(
        f"{base}/",
        host=domain,
        expect_not_5xx=True,
    )
    home["critical"] = True
    probes.append(home)

    # Optional public HTTPS — recorded but not required for pass/fail.
    ext = _http_probe(
        f"https://{domain}/auth/login",
        expect_not_5xx=True,
    )
    ext["critical"] = False
    ext["optional"] = True
    probes.append(ext)

    critical = [p for p in probes if p.get("critical")]
    failed_critical = [p for p in critical if not p.get("ok")]
    ok = not failed_critical
    return {
        "ok": ok,
        "probes": probes,
        "failed": failed_critical,
        "failed_summary": _format_failed_probes(failed_critical),
    }


def _format_failed_probes(failed: list[dict[str, Any]]) -> str:
    if not failed:
        return ""
    parts = []
    for p in failed:
        url = p.get("url") or "?"
        if p.get("status") is not None:
            parts.append(f"{url} → HTTP {p.get('status')} ({p.get('reason') or 'fail'})")
        else:
            parts.append(f"{url} → {p.get('error') or p.get('reason') or 'injoignable'}")
    return "; ".join(parts)


def wait_for_portal_engine_mode(
    settings: Settings,
    expected: str,
    *,
    attempts: int = 15,
    delay_sec: float = 2.0,
) -> dict[str, Any]:
    """Poll nginx WAF snapshot until portal SecRuleEngine matches (watcher lag)."""
    from app.bastion.nginx_waf_reality import portal_engine_mode, read_nginx_waf_reality

    last: str | None = None
    for i in range(attempts):
        active = read_nginx_waf_reality(settings=settings)
        last = portal_engine_mode(active)
        if last == expected:
            return {"ok": True, "mode": last, "attempts": i + 1}
        time.sleep(delay_sec)
    return {"ok": False, "mode": last, "attempts": attempts}


def _force_disarmed_subdomain_files(settings: Settings) -> None:
    """Write Off subdomain connector + Off engine overlay."""
    subdomain_switch_export_path(settings).write_text(
        render_subdomain_switch(enabled=False), encoding="utf-8"
    )
    subdomain_engine_mode_path(settings).write_text(
        render_engine_mode_line(MODE_OFF), encoding="utf-8"
    )


def _force_disarmed_files(settings: Settings) -> None:
    """Write Off switch + Off engine + armed=false (rollback target)."""
    exports = Path(settings.exports_dir)
    exports.mkdir(parents=True, exist_ok=True)
    mod = waf_exports_dir(settings)
    mod.mkdir(parents=True, exist_ok=True)

    switch = portal_switch_export_path(settings)
    switch.write_text(render_portal_switch(enabled=False), encoding="utf-8")
    (mod / "engine-mode-generated.conf").write_text(
        render_engine_mode_line(MODE_OFF), encoding="utf-8"
    )
    write_arm_state(
        settings,
        {
            "armed": False,
            "subdomain_armed": False,
            "family": "portal",
            "target_mode": MODE_OFF,
            "reason": "disarmed",
        },
    )
    _force_disarmed_subdomain_files(settings)


def disarm_engine(
    settings: Settings,
    *,
    actor: str,
    reason: str = "manual_disarm",
) -> dict[str, Any]:
    """Cut ModSecurity connector + SecRuleEngine Off and reload."""
    _force_disarmed_files(settings)
    write_arm_state(
        settings,
        {
            "armed": False,
            "subdomain_armed": False,
            "family": "portal",
            "target_mode": MODE_OFF,
            "reason": reason,
            "actor": actor,
        },
    )
    _force_disarmed_subdomain_files(settings)
    ok, detail = sync_and_reload(settings)
    if ok and "watcher" in detail.lower():
        wait_for_nginx_edge(settings)
    smoke = smoke_portal_probes(settings) if ok else {"ok": False, "probes": [], "failed": []}
    return {
        "ok": bool(ok and smoke.get("ok")),
        "disarmed": True,
        "sync_detail": detail,
        "smoke": smoke,
    }


def reactivate_engine(
    db: Session,
    settings: Settings,
    *,
    actor: str,
    confirm: bool,
    target_mode: str = MODE_DETECTION,
    validate: Callable[[Settings], tuple[bool, str]] | None = None,
    smoke: Callable[[Settings], dict[str, Any]] | None = None,
    sync_reload: Callable[[Settings], tuple[bool, str]] | None = None,
) -> dict[str, Any]:
    """Arm portal ModSecurity (DetectionOnly by default), smoke, rollback on failure."""
    if not confirm:
        return {
            "ok": False,
            "error": "Confirmation requise pour réactiver ModSecurity.",
            "rolled_back": False,
        }

    mode = target_mode if target_mode in {MODE_DETECTION, MODE_ON} else MODE_DETECTION
    # Première réactivation : toujours DetectionOnly, même si le profil est On.
    if mode == MODE_ON:
        mode = MODE_DETECTION

    profile = ensure_active_profile(db)
    previous_mode = profile.mode

    # Snapshot previous arm / files for rollback beyond *.prev
    prev_arm = read_arm_state(settings)

    # Stage: update profile to DetectionOnly so exports match intent
    profile.mode = MODE_DETECTION
    db.commit()

    write_arm_state(
        settings,
        {
            "armed": True,
            "family": "portal",
            "target_mode": MODE_DETECTION,
            "actor": actor,
            "previous_mode": previous_mode,
            "phase": "arming",
        },
    )

    # Write full WAF exports (engine DetectionOnly from profile)
    paths = write_waf_exports(db, settings)
    portal_switch_export_path(settings).write_text(
        render_portal_switch(enabled=True), encoding="utf-8"
    )
    paths[PORTAL_SWITCH_FILENAME] = str(portal_switch_export_path(settings))
    paths[ARM_FILENAME] = str(arm_state_path(settings))

    sync_fn = sync_reload or sync_and_reload
    smoke_fn = smoke or smoke_portal_probes

    sync_ok, sync_detail = sync_fn(settings)
    if not sync_ok:
        _rollback(
            db,
            settings,
            profile=profile,
            previous_mode=previous_mode,
            prev_arm=prev_arm,
            actor=actor,
            reason=f"sync/nginx -t failed: {sync_detail}",
            sync_reload=sync_fn,
        )
        return {
            "ok": False,
            "error": f"Sync/reload échoué — rollback. {sync_detail}",
            "rolled_back": True,
            "paths": paths,
            "sync_detail": sync_detail,
        }

    # Wait for watcher reload when docker exec was skipped (prod).
    if smoke is None and sync_reload is None:
        edge = wait_for_nginx_edge(settings)
        if not edge.get("ok"):
            time.sleep(RELOAD_WAIT_SEC)
        engine_wait = wait_for_portal_engine_mode(settings, MODE_DETECTION)
        if not engine_wait.get("ok"):
            _rollback(
                db,
                settings,
                profile=profile,
                previous_mode=previous_mode,
                prev_arm=prev_arm,
                actor=actor,
                reason="engine_mode_not_applied",
                sync_reload=sync_fn,
            )
            return {
                "ok": False,
                "error": (
                    "nginx n'a pas basculé en DetectionOnly après reload "
                    f"(mode snapshot={engine_wait.get('mode')!r}). "
                    "Vérifier le watcher bastion-nginx ou forcer "
                    "sync-exports-to-confd.sh + reload."
                ),
                "rolled_back": True,
                "paths": paths,
                "engine_wait": engine_wait,
                "sync_detail": sync_detail,
            }

    smoke_result = smoke_fn(settings)
    if not smoke_result.get("ok"):
        _rollback(
            db,
            settings,
            profile=profile,
            previous_mode=previous_mode,
            prev_arm=prev_arm,
            actor=actor,
            reason="smoke_failed",
            sync_reload=sync_fn,
        )
        failed = smoke_result.get("failed") or []
        summary = smoke_result.get("failed_summary") or _format_failed_probes(failed)
        err = (
            "Smoke post-reload en échec — rollback automatique vers Off."
            + (f" Détail : {summary}" if summary else "")
        )
        return {
            "ok": False,
            "error": err,
            "rolled_back": True,
            "paths": paths,
            "smoke": smoke_result,
            "failed_probes": failed,
            "failed_summary": summary,
            "sync_detail": sync_detail,
        }

    write_arm_state(
        settings,
        {
            "armed": True,
            "family": "portal",
            "target_mode": MODE_DETECTION,
            "actor": actor,
            "previous_mode": previous_mode,
            "phase": "active",
            "last_smoke_ok": True,
            "last_smoke_at": datetime.now(timezone.utc).isoformat(),
            "smoke": smoke_result,
        },
    )
    record_waf_apply_metadata(
        settings,
        actor=actor,
        nginx_t_ok=True,
        nginx_t_detail=f"reactivate ok; {sync_detail}",
        nginx_t_skipped=False,
    )
    return {
        "ok": True,
        "rolled_back": False,
        "paths": paths,
        "mode": MODE_DETECTION,
        "family": "portal",
        "smoke": smoke_result,
        "sync_detail": sync_detail,
        "effective": read_effective_status(settings),
        "message": (
            "Moteur portal réactivé en DetectionOnly. Smoke OK. "
            "Passer en On seulement après période d'observation."
        ),
    }


def wait_for_subdomain_engine_mode(
    settings: Settings,
    expected: str,
    *,
    attempts: int = 15,
    delay_sec: float = 2.0,
) -> dict[str, Any]:
    """Poll nginx WAF snapshot until subdomain SecRuleEngine matches."""
    from app.bastion.nginx_waf_reality import read_nginx_waf_reality, subdomain_engine_mode

    last: str | None = None
    for i in range(attempts):
        active = read_nginx_waf_reality(settings=settings)
        last = subdomain_engine_mode(active)
        if last == expected:
            return {"ok": True, "mode": last, "attempts": i + 1}
        time.sleep(delay_sec)
    return {"ok": False, "mode": last, "attempts": attempts}


def smoke_subdomain_probes(db: Session, settings: Settings) -> dict[str, Any]:
    """HTTP smoke on each enabled subdomain_proxy Host (edge :8080, no 5xx)."""
    hosts = list_subdomain_smoke_hosts(db)[:SUBDOMAIN_SMOKE_HOST_LIMIT]
    if not hosts:
        return {
            "ok": False,
            "probes": [],
            "failed": [{"reason": "Aucune app subdomain_proxy activée avec FQDN."}],
            "failed_summary": "Aucune app subdomain_proxy activée avec FQDN.",
        }

    base = "http://nginx:8080"
    probes: list[dict[str, Any]] = []
    for host in hosts:
        probe = _http_probe(f"{base}/healthz", host=host, expect_not_5xx=True)
        probe["critical"] = True
        probe["subdomain_host"] = host
        probes.append(probe)

    failed_critical = [p for p in probes if p.get("critical") and not p.get("ok")]
    ok = not failed_critical
    return {
        "ok": ok,
        "probes": probes,
        "failed": failed_critical,
        "failed_summary": _format_failed_probes(failed_critical),
        "hosts": hosts,
    }


def reactivate_subdomain_engine(
    db: Session,
    settings: Settings,
    *,
    actor: str,
    confirm: bool,
    validate: Callable[[Settings], tuple[bool, str]] | None = None,
    smoke: Callable[[Session, Settings], dict[str, Any]] | None = None,
    sync_reload: Callable[[Settings], tuple[bool, str]] | None = None,
) -> dict[str, Any]:
    """Arm subdomain ModSecurity (DetectionOnly) after portal is armed; smoke + rollback."""
    if not confirm:
        return {
            "ok": False,
            "error": "Confirmation requise pour réactiver ModSecurity subdomain.",
            "rolled_back": False,
        }

    arm = read_arm_state(settings)
    if not arm.get("armed"):
        return {
            "ok": False,
            "error": (
                "Le moteur portal doit être armé (DetectionOnly) avant les sous-domaines."
            ),
            "rolled_back": False,
        }
    if read_subdomain_armed(settings):
        return {
            "ok": False,
            "error": "ModSecurity subdomain déjà armé.",
            "rolled_back": False,
        }

    hosts = list_subdomain_smoke_hosts(db)
    if not hosts:
        return {
            "ok": False,
            "error": "Aucune application subdomain_proxy activée avec FQDN.",
            "rolled_back": False,
        }

    prev_arm = dict(arm)
    mod_dir = waf_exports_dir(settings)
    mod_dir.mkdir(parents=True, exist_ok=True)
    switch_path = subdomain_switch_export_path(settings)
    engine_path = subdomain_engine_mode_path(settings)

    from app.bastion.nginx_waf_export import _backup_file

    _backup_file(switch_path)
    _backup_file(engine_path)
    _backup_file(arm_state_path(settings))

    switch_path.write_text(render_subdomain_switch(enabled=True), encoding="utf-8")
    engine_path.write_text(render_engine_mode_line(MODE_DETECTION), encoding="utf-8")

    body = dict(prev_arm)
    body.update(
        {
            "subdomain_armed": True,
            "subdomain": {
                "armed": True,
                "target_mode": MODE_DETECTION,
                "actor": actor,
                "phase": "arming",
                "smoke_hosts": hosts[:SUBDOMAIN_SMOKE_HOST_LIMIT],
            },
        }
    )
    write_arm_state(settings, body)

    paths = {
        SUBDOMAIN_SWITCH_FILENAME: str(switch_path),
        ENGINE_SUBDOMAIN_MODE_FILENAME: str(engine_path),
        ARM_FILENAME: str(arm_state_path(settings)),
    }

    sync_fn = sync_reload or sync_and_reload
    smoke_fn = smoke or smoke_subdomain_probes

    sync_ok, sync_detail = sync_fn(settings)
    if not sync_ok:
        _rollback_subdomain(
            settings,
            prev_arm=prev_arm,
            actor=actor,
            reason=f"sync/nginx -t failed: {sync_detail}",
            sync_reload=sync_fn,
        )
        return {
            "ok": False,
            "error": f"Sync/reload échoué — rollback subdomain. {sync_detail}",
            "rolled_back": True,
            "paths": paths,
            "sync_detail": sync_detail,
        }

    if smoke is None and sync_reload is None:
        edge = wait_for_nginx_edge(settings)
        if not edge.get("ok"):
            time.sleep(RELOAD_WAIT_SEC)
        engine_wait = wait_for_subdomain_engine_mode(settings, MODE_DETECTION)
        if not engine_wait.get("ok"):
            _rollback_subdomain(
                settings,
                prev_arm=prev_arm,
                actor=actor,
                reason="subdomain_engine_mode_not_applied",
                sync_reload=sync_fn,
            )
            return {
                "ok": False,
                "error": (
                    "nginx n'a pas basculé subdomain en DetectionOnly après reload "
                    f"(mode snapshot={engine_wait.get('mode')!r})."
                ),
                "rolled_back": True,
                "paths": paths,
                "engine_wait": engine_wait,
                "sync_detail": sync_detail,
            }

    smoke_result = smoke_fn(db, settings)
    if not smoke_result.get("ok"):
        _rollback_subdomain(
            settings,
            prev_arm=prev_arm,
            actor=actor,
            reason="subdomain_smoke_failed",
            sync_reload=sync_fn,
        )
        summary = smoke_result.get("failed_summary") or _format_failed_probes(
            smoke_result.get("failed") or []
        )
        return {
            "ok": False,
            "error": (
                "Smoke subdomain en échec — rollback automatique vers Off."
                + (f" Détail : {summary}" if summary else "")
            ),
            "rolled_back": True,
            "paths": paths,
            "smoke": smoke_result,
            "failed_summary": summary,
            "sync_detail": sync_detail,
        }

    final_arm = dict(read_arm_state(settings))
    sub = dict(final_arm.get("subdomain") or {})
    sub.update(
        {
            "armed": True,
            "target_mode": MODE_DETECTION,
            "actor": actor,
            "phase": "active",
            "last_smoke_ok": True,
            "last_smoke_at": datetime.now(timezone.utc).isoformat(),
            "smoke": smoke_result,
        }
    )
    final_arm["subdomain_armed"] = True
    final_arm["subdomain"] = sub
    write_arm_state(settings, final_arm)

    record_waf_apply_metadata(
        settings,
        actor=actor,
        nginx_t_ok=True,
        nginx_t_detail=f"reactivate subdomain ok; {sync_detail}",
        nginx_t_skipped=False,
    )
    return {
        "ok": True,
        "rolled_back": False,
        "paths": paths,
        "mode": MODE_DETECTION,
        "family": "subdomain",
        "smoke": smoke_result,
        "sync_detail": sync_detail,
        "smoke_hosts": hosts[:SUBDOMAIN_SMOKE_HOST_LIMIT],
        "message": (
            f"Moteur subdomain réactivé en DetectionOnly ({len(hosts[:SUBDOMAIN_SMOKE_HOST_LIMIT])} "
            "sonde(s)). Smoke OK. Passer en On seulement après observation."
        ),
    }


def promote_subdomain_engine_to_on(
    db: Session,
    settings: Settings,
    *,
    actor: str,
    confirm: bool,
    smoke: Callable[[Session, Settings], dict[str, Any]] | None = None,
    sync_reload: Callable[[Settings], tuple[bool, str]] | None = None,
) -> dict[str, Any]:
    """Passe subdomain de DetectionOnly à On (smoke + rollback vers DetectionOnly)."""
    if not confirm:
        return {
            "ok": False,
            "error": "Confirmation requise pour promouvoir ModSecurity subdomain en On.",
            "rolled_back": False,
        }

    if not read_arm_state(settings).get("armed"):
        return {
            "ok": False,
            "error": "Le moteur portal doit être armé avant de promouvoir les sous-domaines.",
            "rolled_back": False,
        }
    if not read_subdomain_armed(settings):
        return {
            "ok": False,
            "error": (
                "ModSecurity subdomain doit d'abord être réactivé en DetectionOnly "
                "(onglet Réactivation)."
            ),
            "rolled_back": False,
        }

    profile = ensure_active_profile(db)
    if profile.mode != MODE_ON:
        return {
            "ok": False,
            "error": (
                "Le profil WAF doit être en mode On (blocage) avant de promouvoir "
                "les sous-domaines. Enregistrer le profil puis réessayer."
            ),
            "rolled_back": False,
        }

    arm = read_arm_state(settings)
    sub = arm.get("subdomain") if isinstance(arm.get("subdomain"), dict) else {}
    current_target = str(sub.get("target_mode") or MODE_DETECTION)
    if current_target == MODE_ON:
        return {
            "ok": False,
            "error": "ModSecurity subdomain est déjà en cible On.",
            "rolled_back": False,
        }

    hosts = list_subdomain_smoke_hosts(db)
    if not hosts:
        return {
            "ok": False,
            "error": "Aucune application subdomain_proxy activée avec FQDN.",
            "rolled_back": False,
        }

    prev_arm = dict(arm)
    engine_path = subdomain_engine_mode_path(settings)
    mod_dir = waf_exports_dir(settings)
    mod_dir.mkdir(parents=True, exist_ok=True)

    from app.bastion.nginx_waf_export import _backup_file

    _backup_file(engine_path)
    _backup_file(arm_state_path(settings))

    engine_path.write_text(render_engine_mode_line(MODE_ON), encoding="utf-8")

    body = dict(prev_arm)
    body.update(
        {
            "subdomain_armed": True,
            "subdomain": {
                **dict(sub),
                "armed": True,
                "target_mode": MODE_ON,
                "actor": actor,
                "phase": "promoting",
                "smoke_hosts": hosts[:SUBDOMAIN_SMOKE_HOST_LIMIT],
            },
        }
    )
    write_arm_state(settings, body)

    paths = {
        ENGINE_SUBDOMAIN_MODE_FILENAME: str(engine_path),
        ARM_FILENAME: str(arm_state_path(settings)),
    }

    sync_fn = sync_reload or sync_and_reload
    smoke_fn = smoke or smoke_subdomain_probes

    sync_ok, sync_detail = sync_fn(settings)
    if not sync_ok:
        _rollback_subdomain_promote(
            settings,
            prev_arm=prev_arm,
            actor=actor,
            reason=f"sync/nginx -t failed: {sync_detail}",
            sync_reload=sync_fn,
        )
        return {
            "ok": False,
            "error": f"Sync/reload échoué — retour DetectionOnly. {sync_detail}",
            "rolled_back": True,
            "paths": paths,
            "sync_detail": sync_detail,
        }

    if smoke is None and sync_reload is None:
        edge = wait_for_nginx_edge(settings)
        if not edge.get("ok"):
            time.sleep(RELOAD_WAIT_SEC)
        engine_wait = wait_for_subdomain_engine_mode(settings, MODE_ON)
        if not engine_wait.get("ok"):
            _rollback_subdomain_promote(
                settings,
                prev_arm=prev_arm,
                actor=actor,
                reason="subdomain_engine_mode_on_not_applied",
                sync_reload=sync_fn,
            )
            return {
                "ok": False,
                "error": (
                    "nginx n'a pas basculé subdomain en On après reload "
                    f"(mode snapshot={engine_wait.get('mode')!r})."
                ),
                "rolled_back": True,
                "paths": paths,
                "engine_wait": engine_wait,
                "sync_detail": sync_detail,
            }

    smoke_result = smoke_fn(db, settings)
    if not smoke_result.get("ok"):
        _rollback_subdomain_promote(
            settings,
            prev_arm=prev_arm,
            actor=actor,
            reason="subdomain_promote_smoke_failed",
            sync_reload=sync_fn,
        )
        summary = smoke_result.get("failed_summary") or _format_failed_probes(
            smoke_result.get("failed") or []
        )
        return {
            "ok": False,
            "error": (
                "Smoke subdomain en échec — retour automatique en DetectionOnly."
                + (f" Détail : {summary}" if summary else "")
            ),
            "rolled_back": True,
            "paths": paths,
            "smoke": smoke_result,
            "failed_summary": summary,
            "sync_detail": sync_detail,
        }

    final_arm = dict(read_arm_state(settings))
    sub_final = dict(final_arm.get("subdomain") or {})
    sub_final.update(
        {
            "armed": True,
            "target_mode": MODE_ON,
            "actor": actor,
            "phase": "active",
            "last_smoke_ok": True,
            "last_smoke_at": datetime.now(timezone.utc).isoformat(),
            "smoke": smoke_result,
        }
    )
    final_arm["subdomain_armed"] = True
    final_arm["subdomain"] = sub_final
    write_arm_state(settings, final_arm)

    record_waf_apply_metadata(
        settings,
        actor=actor,
        nginx_t_ok=True,
        nginx_t_detail=f"promote subdomain On ok; {sync_detail}",
        nginx_t_skipped=False,
    )
    return {
        "ok": True,
        "rolled_back": False,
        "paths": paths,
        "mode": MODE_ON,
        "family": "subdomain",
        "smoke": smoke_result,
        "sync_detail": sync_detail,
        "smoke_hosts": hosts[:SUBDOMAIN_SMOKE_HOST_LIMIT],
        "message": (
            f"Moteur subdomain promu en On ({len(hosts[:SUBDOMAIN_SMOKE_HOST_LIMIT])} "
            "sonde(s)). Smoke OK — blocage CRS actif sur les sous-domaines."
        ),
    }


def _rollback_subdomain_promote(
    settings: Settings,
    *,
    prev_arm: dict[str, Any],
    actor: str,
    reason: str,
    sync_reload: Callable[[Settings], tuple[bool, str]] | None = None,
) -> None:
    """Restore DetectionOnly after a failed On promote (keep subdomain armed)."""
    logger.warning("waf subdomain promote rollback: %s", reason)
    from app.bastion.nginx_waf_export import _restore_file

    if not _restore_file(subdomain_engine_mode_path(settings)):
        subdomain_engine_mode_path(settings).write_text(
            render_engine_mode_line(MODE_DETECTION), encoding="utf-8"
        )
    restored = dict(prev_arm)
    restored["subdomain_armed"] = True
    if isinstance(restored.get("subdomain"), dict):
        sub = dict(restored["subdomain"])
        sub["armed"] = True
        sub["target_mode"] = MODE_DETECTION
        sub["reason"] = reason
        sub["rolled_back"] = True
        sub["actor"] = actor
        sub["phase"] = "active"
        restored["subdomain"] = sub
    else:
        restored["subdomain"] = {
            "armed": True,
            "target_mode": MODE_DETECTION,
            "reason": reason,
            "rolled_back": True,
            "actor": actor,
            "phase": "active",
        }
    write_arm_state(settings, restored)
    sync_fn = sync_reload or sync_and_reload
    try:
        sync_fn(settings)
    except Exception:  # noqa: BLE001
        logger.exception("sync after subdomain promote rollback failed")


def _rollback_subdomain(
    settings: Settings,
    *,
    prev_arm: dict[str, Any],
    actor: str,
    reason: str,
    sync_reload: Callable[[Settings], tuple[bool, str]] | None = None,
) -> None:
    logger.warning("waf subdomain reactivation rollback: %s", reason)
    from app.bastion.nginx_waf_export import _restore_file

    _restore_file(subdomain_switch_export_path(settings))
    _restore_file(subdomain_engine_mode_path(settings))
    _force_disarmed_subdomain_files(settings)
    restored = dict(prev_arm)
    restored["subdomain_armed"] = False
    if isinstance(restored.get("subdomain"), dict):
        sub = dict(restored["subdomain"])
        sub["armed"] = False
        sub["reason"] = reason
        sub["rolled_back"] = True
        sub["actor"] = actor
        restored["subdomain"] = sub
    write_arm_state(settings, restored)
    sync_fn = sync_reload or sync_and_reload
    try:
        sync_fn(settings)
    except Exception:  # noqa: BLE001
        logger.exception("sync after subdomain rollback failed")


def _rollback(
    db: Session,
    settings: Settings,
    *,
    profile: WafProfile,
    previous_mode: str,
    prev_arm: dict[str, Any],
    actor: str,
    reason: str,
    sync_reload: Callable[[Settings], tuple[bool, str]] | None = None,
) -> None:
    logger.warning("waf reactivation rollback: %s", reason)
    restore_waf_exports_previous(settings)
    _force_disarmed_files(settings)
    profile.mode = MODE_OFF
    db.commit()
    write_arm_state(
        settings,
        {
            "armed": False,
            "family": "portal",
            "target_mode": MODE_OFF,
            "actor": actor,
            "reason": reason,
            "rolled_back": True,
            "previous_arm": {
                k: prev_arm.get(k) for k in ("armed", "target_mode", "phase") if k in prev_arm
            },
        },
    )
    sync_fn = sync_reload or sync_and_reload
    try:
        sync_fn(settings)
    except Exception:  # noqa: BLE001
        logger.exception("sync after rollback failed")
    if sync_reload is None:
        try:
            smoke_portal_probes(settings)
        except Exception:  # noqa: BLE001
            logger.exception("smoke after rollback failed")
