# Secrets scan on every PR and push to default branches.
# Personal accounts: no GITLEAKS_LICENSE required.
# Actions pinned to full commit SHAs (Sonar githubactions:S7637).
name: gitleaks

on:
  pull_request:
  push:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
